aws/aws-cryptographic-material-providers-library

- cfn/CI.yaml
*Issue #, if available:*
*Description of changes:*
*Squash/merge commit message, if applicable:*
> chore: give esdk dotnet codebuild access to resources

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/AwsCryptographyMaterialProvidersOperations.dfy
In Java `smithy-dafny` represents integers as `int`. This is a problem because for an optional member
because an `int` will always have a value.
If it is not set then the value will be `0`.
This means that as the value crosses the verification boundary what should be translated into `None` is `Some(0)`.
This would result in the CMC never pruning out values and the cache may grow without bound.
This did not impact the `Default` or `No` CMC `CacheType`s. It *did* impact the `SingleThreaded`, `MultiThreaded`, and `StormTracking` CMC `CacheType`s
> fix: Default entryPruningTailSize

- .github/workflows/library_dafny_format.yml
> chore: Update dafny format

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- CHANGELOG.md
> chore: Version Bump

- codebuild/release/release-prod.yml
- codebuild/release/validate-release.yml
- codebuild/staging/release-staging.yml
- codebuild/staging/validate-staging.yml
*Issue #, if available:*
*Description of changes:*
*Squash/merge commit message, if applicable:*
> chore: update java codebuild to dafny 4.2.0

- .github/workflows/ci_static-analysis.yaml
- .github/workflows/dafny_version.yaml
- .github/workflows/daily_ci.yml
- .github/workflows/manual.yml
- .github/workflows/pull.yml
- .github/workflows/push.yml
- project.properties
Testing ways to consolidate the dafny version
> consolidate dafny version

- .github/workflows/nightly_dafny.yml
> fix(GHW): typo lead to two verification, no format

- ComAmazonawsDynamodb/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/services/dynamodb/internaldafny/Shim.java
- ComAmazonawsDynamodb/runtimes/net/Generated/DynamoDBv2Shim.cs
> feat(DDB): newest polymorph for newest shims. Catch all exceptions. DDB only

- AwsCryptographicMaterialProviders/runtimes/java/README.md
- AwsCryptographicMaterialProviders/runtimes/net/README.md
- README.md
> docs(README): update README for repo rename update

- AwsCryptographicMaterialProviders/codebuild/release-prod.yml
- AwsCryptographyPrimitives/codebuild/release-prod.yml
- ComAmazonawsDynamodb/codebuild/release-prod.yml
- ComAmazonawsKms/codebuild/release-prod.yml
- StandardLibrary/codebuild/release-prod.yml
> chore: retrieve netstandard2.0 signed dll to publish

- cfn/CB-Staging.yml
- cfn/CI.yaml
- cfn/code_build_parameter_map.json
- cfn/net/CB-Release.yml
> chore(CFN): update cfn repo names

- .github/dependabot.yml
Turns out you specify the directory, not the project file.
See: https://github.com/microsoft/CsWin32/blob/18302d247977af90af649e32235eec305dcf942f/.azuredevops/dependabot.yml#L6
> chore(.NET): fix Nuget Dependabot

- AwsCryptographicMaterialProviders/runtimes/java/README.md
- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs
- AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj
- AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs
- AwsCryptographyPrimitives/runtimes/net/Crypto.csproj
- CHANGELOG.md
- ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs
- ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj
- ComAmazonawsKms/runtimes/net/AWS-KMS.csproj
- ComAmazonawsKms/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/STD.csproj
> chore: bump version

- AwsCryptographicMaterialProviders/codebuild/release-prod.yml
- AwsCryptographicMaterialProviders/codebuild/release-staging.yml
- AwsCryptographicMaterialProviders/codebuild/sign.yml
- AwsCryptographicMaterialProviders/codebuild/test-prod.yml
- AwsCryptographyPrimitives/codebuild/release-prod.yml
- AwsCryptographyPrimitives/codebuild/release-staging.yml
- AwsCryptographyPrimitives/codebuild/sign.yml
- AwsCryptographyPrimitives/codebuild/test-prod.yml
- ComAmazonawsDynamodb/codebuild/release-prod.yml
- ComAmazonawsDynamodb/codebuild/release-staging.yml
- ComAmazonawsDynamodb/codebuild/sign.yml
- ComAmazonawsDynamodb/codebuild/test-prod.yml
- ComAmazonawsKms/codebuild/release-prod.yml
- ComAmazonawsKms/codebuild/release-staging.yml
- ComAmazonawsKms/codebuild/sign.yml
- ComAmazonawsKms/codebuild/test-prod.yml
- StandardLibrary/codebuild/release-prod.yml
- StandardLibrary/codebuild/release-staging.yml
- StandardLibrary/codebuild/sign.yml
- StandardLibrary/codebuild/test-prod.yml
- codebuild/release/release-prod.yml
- codebuild/release/validate-release.yml
- codebuild/staging/release-staging.yml
- codebuild/staging/validate-staging.yml
> chore: fix name in release

- AwsCryptographicMaterialProviders/codebuild/release-prod.yml
- AwsCryptographicMaterialProviders/codebuild/release-staging.yml
- AwsCryptographicMaterialProviders/codebuild/sign.yml
- AwsCryptographicMaterialProviders/codebuild/test-prod.yml
- AwsCryptographyPrimitives/codebuild/release-prod.yml
- AwsCryptographyPrimitives/codebuild/release-staging.yml
- AwsCryptographyPrimitives/codebuild/sign.yml
- AwsCryptographyPrimitives/codebuild/test-prod.yml
- ComAmazonawsDynamodb/codebuild/release-prod.yml
- ComAmazonawsDynamodb/codebuild/release-staging.yml
- ComAmazonawsDynamodb/codebuild/sign.yml
- ComAmazonawsDynamodb/codebuild/test-prod.yml
- ComAmazonawsKms/codebuild/release-prod.yml
- ComAmazonawsKms/codebuild/release-staging.yml
- ComAmazonawsKms/codebuild/sign.yml
- ComAmazonawsKms/codebuild/test-prod.yml
- StandardLibrary/codebuild/release-prod.yml
- StandardLibrary/codebuild/release-staging.yml
- StandardLibrary/codebuild/sign.yml
- StandardLibrary/codebuild/test-prod.yml
- codebuild/release/release-prod.yml
- codebuild/release/validate-release.yml
- codebuild/staging/release-staging.yml
- codebuild/staging/validate-staging.yml
> chore: comment out export

- AwsCryptographicMaterialProviders/codebuild/release-staging.yml
- AwsCryptographicMaterialProviders/codebuild/sign.yml
- AwsCryptographicMaterialProviders/codebuild/test-prod.yml
- AwsCryptographyPrimitives/codebuild/release-staging.yml
- AwsCryptographyPrimitives/codebuild/sign.yml
- AwsCryptographyPrimitives/codebuild/test-prod.yml
- ComAmazonawsDynamodb/codebuild/release-staging.yml
- ComAmazonawsDynamodb/codebuild/sign.yml
- ComAmazonawsDynamodb/codebuild/test-prod.yml
- ComAmazonawsKms/codebuild/release-staging.yml
- ComAmazonawsKms/codebuild/sign.yml
- ComAmazonawsKms/codebuild/test-prod.yml
- StandardLibrary/codebuild/release-staging.yml
- StandardLibrary/codebuild/sign.yml
- StandardLibrary/codebuild/test-prod.yml
> chore: pass in framework

- CHANGELOG.md
> docs: CHANGELOG 1.2.0

- codebuild/release/release-prod.yml
- codebuild/release/validate-release.yml
- codebuild/staging/release-staging.yml
- codebuild/staging/validate-staging.yml
> fix: dir name in java mpl release process

- .releaserc.cjs
- Makefile
> chore: fix releaserc for new build changes and add make command

- StandardLibrary/test/TestComputeSetToOrderedSequenceCharLess.dfy
> chore(StandardLibrary): Add info to ComputeSetToOrderedSequence test

- cfn/CI-Bot.yml
> chore: remove loose access principal to role

- cfn/CI.yaml
Allow the Staging Repo to use the AWS Resources needed to test this library.
> chore(cfn): allow Staging Repo access to testing resources

- .github/workflows/semantic_release.yml
> chore: fix gha semver

- .github/workflows/semantic_release.yml
> chore: gh_token vs github_token

- .github/workflows/semantic_release.yml
> chore: fix permissions gha

- .github/workflows/semantic_release.yml
> chore: abb back env

- .github/workflows/java-release.yml
> chore: fix workflow name

- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/ParseJsonManifests.dfy
> chore: add example of tail recursion

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/test/Keyrings/TestRawAESKeyring.dfy
Removed a ghost var which was not used. 
> Remove redundant ghost var

- .github/workflows/library_dafny_verification.yml
- .github/workflows/library_java_tests.yml
- .github/workflows/library_net_tests.yml
- .github/workflows/sem_ver.yml
- .github/workflows/semantic_release.yml
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestVersionKey.dfy
> chore: add test for VersionKey with an MRK

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
> chore: bump to SNAPSHOT version to pick up and test latest

- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/Index.dfy
- TestVectorsAwsCryptographicMaterialProviders/runtimes/net/TestVectors.csproj
> chore: the test vectors should not define a Main

- .github/workflows/smithy-diff.yml
- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/commitment.smithy
> chore(CI): add smithy diff checker gha

- .github/workflows/nightly_dafny.yml
- .github/workflows/smithy-diff.yml
- AwsCryptographyPrimitives/runtimes/net/Crypto.csproj
- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/Index.dfy
- TestVectorsAwsCryptographicMaterialProviders/runtimes/net/TestVectors.csproj
> chore(.NET): deps

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
> chore(Java): enable SNAPSHOT testing

- .github/workflows/nightly_dafny.yml
This automation creates a lot of noise on `dafny-lang/dafny`. Instead of always creating new issues, we create a comment, when possible.
> chore: Try to update existing issues

- ComAmazonawsDynamodb/runtimes/python/src/com_amazonaws_dynamodb/internaldafny/extern/Com_Amazonaws_Dynamodb.py
- ComAmazonawsDynamodb/runtimes/python/src/com_amazonaws_dynamodb/internaldafny/extern/__init__.py
> Python: DDB extern

- AwsCryptographyPrimitives/runtimes/java/src/main/java/ECDH/ECCUtils.java
- AwsCryptographyPrimitives/runtimes/net/Extern/ECDH.cs
- AwsCryptographyPrimitives/src/ECDH.dfy
- AwsCryptographyPrimitives/test/TestECDH.dfy
> chore: Add more robust public key validation tests

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
> chore: enable SNAPSHOT testing

- AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs
- AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj
- AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs
- AwsCryptographyPrimitives/runtimes/net/Crypto.csproj
- ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs
- ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj
- ComAmazonawsKms/runtimes/net/AWS-KMS.csproj
- ComAmazonawsKms/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/STD.csproj
> chore(.NET): bump projects to 1.5.0

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs
- AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj
- AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs
- AwsCryptographyPrimitives/runtimes/net/Crypto.csproj
- CHANGELOG.md
- ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs
- ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj
- ComAmazonawsKms/runtimes/net/AWS-KMS.csproj
- ComAmazonawsKms/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/STD.csproj
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
> chore(release): 1.5.1

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
> feat(post-release): Change back to 1.5.1-SNAPSHOT

- .releaserc.cjs
- project.properties
> chore: add mpl version to project.properties

- ComAmazonawsDynamodb/codebuild/test-prod.yml
> chore: fix typos in test-prod.yml 

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/RawECDHKeyring.dfy
> chore: remove redundant assignment

- StandardLibrary/src/GetOpt.dfy
> chore: update Dafny code to appease Rust code generation

- AwsCryptographicMaterialProviders/codebuild/release-python/prod-release.yml
- AwsCryptographicMaterialProviders/codebuild/release-python/test-release.yml
- AwsCryptographicMaterialProviders/codebuild/release-python/validate.yml
- AwsCryptographicMaterialProviders/runtimes/python/dev_requirements/release-requirements.txt
- AwsCryptographicMaterialProviders/runtimes/python/park.cfg
- AwsCryptographicMaterialProviders/runtimes/python/tox.ini
- cfn/python/MPL-Python.yml
> chore(release): add cfn and codebuild files for release

- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/internaldafny/extern/__init__.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/internaldafny/extern/wrapped_mpl.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/internaldafny/extern/GetTestDirectoryExtern.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/internaldafny/extern/__init__.py
> Python: Testvectors Externs

- .github/workflows/check-files.yml
- .releaserc.cjs
> chore(release): .releaserc.cjs updates

- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviders/__init__.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviders/shim.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/__init__.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/aws_sdk_to_dafny.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/client.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/config.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/dafnyImplInterface.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/dafny_protocol.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/dafny_to_aws_sdk.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/dafny_to_smithy.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/deserialize.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/errors.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/models.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/plugin.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/serialize.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviderstestvectorkeys/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/smithy_to_dafny.py
> Python: TestVectors Smithy-generated code

- AwsCryptographyPrimitives/test/TestECDH.dfy
> test: More ECDH known value tests

- AwsCryptographyPrimitives/test/TestECDH.dfy
> fix: add ECDH error message for Rust

- AwsCryptographyPrimitives/runtimes/java/src/main/java/ECDH/DeriveSharedSecret.java
- AwsCryptographyPrimitives/runtimes/java/src/main/java/ECDH/ECCUtils.java
> chore: Change exception raised for SM2

- AwsCryptographyPrimitives/test/TestECDH.dfy
> chore: add intermediate test for compression test

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/RawECDHKeyring.dfy
- AwsCryptographyPrimitives/test/TestECDH.dfy
Remove a case-based `if` statement, as it caused errors about non-determinism.
Reduce resource use to fix a verification failure along the way.
> chore: remove case-based if statement

- .github/workflows/pull.yml
poetic inspiration: https://github.com/smithy-lang/smithy-dafny/pull/554
> chore(ci): make all pull.yml jobs required in branch protection automatically

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- project.properties
> chore(CI): enable local testing

- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_keystore/client.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_keystore/config.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_keystore/errors.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_keystore/models.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_keystore/plugin.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/client.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/config.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/errors.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/models.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/plugin.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/references.py
- AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/client.py
- AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/config.py
- AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/errors.py
- AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/models.py
- AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/plugin.py
- ComAmazonawsDynamodb/runtimes/python/src/aws_cryptography_internal_dynamodb/smithygenerated/com_amazonaws_dynamodb/shim.py
- ComAmazonawsKms/runtimes/python/src/aws_cryptography_internal_kms/smithygenerated/com_amazonaws_kms/shim.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/client.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/config.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/errors.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/models.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/plugin.py
Run `polymorph_python`. This PR only affects docstrings.
> Python: Format docstrings

- .releaserc.cjs
- AwsCryptographicMaterialProviders/runtimes/python/.gitignore
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/internaldafny/generated/dafny_src-py.dtr
- AwsCryptographyPrimitives/runtimes/python/.gitignore
- AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/internaldafny/generated/dafny_src-py.dtr
- ComAmazonawsDynamodb/runtimes/python/.gitignore
- ComAmazonawsDynamodb/runtimes/python/src/aws_cryptography_internal_dynamodb/internaldafny/generated/dafny_src-py.dtr
- ComAmazonawsKms/runtimes/python/.gitignore
- ComAmazonawsKms/runtimes/python/src/aws_cryptography_internal_kms/internaldafny/generated/dafny_src-py.dtr
- Makefile
- StandardLibrary/runtimes/python/.gitignore
- StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/generated/dafny_src-py.dtr
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/.gitignore
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/internaldafny/generated/dafny_src-py.dtr
> Python: Regenerate and commit dtr files on release

- .github/workflows/smithy-diff.yml
- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/cmms.smithy
> chore(CI): make smithy diff checker smarter

- .github/workflows/smithy-diff.yml
- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/cmms.smithy
> chore: test smithy diff

- StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/__init__.py
> Python: Add missing file

- .github/workflows/smithy-diff.yml
> chore: merge from main

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs
- AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj
- AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs
- AwsCryptographyPrimitives/runtimes/net/Crypto.csproj
- CHANGELOG.md
- ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs
- ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj
- ComAmazonawsKms/runtimes/net/AWS-KMS.csproj
- ComAmazonawsKms/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/STD.csproj
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- project.properties
Update changelog for release version 1.7.0
> chore(release): 1.7.0

- .github/actions/polymorph_codegen/action.yml
- .github/workflows/daily_ci.yml
- .github/workflows/library_codegen.yml
- .github/workflows/library_interop_tests.yml
- .github/workflows/library_python_tests.yml
- .github/workflows/manual.yml
- .github/workflows/nightly_dafny.yml
- .github/workflows/pull.yml
- .github/workflows/push.yml
Github workflows for Python MPL.
These (mostly) succeed with other code on the `lucmcdon/python-mpl-v2` branch: #550 
See a sample CI run: https://github.com/aws/aws-cryptographic-material-providers-library/actions/runs/10949507271/job/30402913752
> Python: GHA workflows

- cfn/python/MPL-Python.yml
Commit the current state of Python release CFN.
Currently, Prod release resources are commented out in AWS Console.
I also bump the default CB runner to 7.0, which has Python 3.11+.
> Python: Commit current CFN state

- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/internaldafny/generated/dafny_src-py.dtr
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/dafny_to_smithy.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/models.py
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/smithy_to_dafny.py
Run `make polymorph_python` with most recent Dafny changes.
> Python: Re-polymorph (shared cache)

- AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/internaldafny/extern/ECDH.py
- StandardLibrary/runtimes/python/pyproject.toml
> chore(Python): Update ECDH extern, pin DafnyRuntimePython version

- .gitignore
- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographyPrimitives/runtimes/java/build.gradle.kts
- ComAmazonawsDynamodb/runtimes/java/build.gradle.kts
- ComAmazonawsKms/runtimes/java/build.gradle.kts
- StandardLibrary/runtimes/java/build.gradle.kts
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
> chore(Java): bump conversion library

- StandardLibrary/runtimes/java/src/main/java/Time/__default.java
- StandardLibrary/runtimes/net/Extern/Time.cs
- StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/extern/Time.py
- StandardLibrary/src/Time.dfy
- StandardLibrary/test/Time.dfy
> chore: add millisecond time

- cfn/python/MPL-Python.yml
> chore(Python): Add Prod release CFN

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs
- AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj
- AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml
- AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs
- AwsCryptographyPrimitives/runtimes/net/Crypto.csproj
- AwsCryptographyPrimitives/runtimes/python/pyproject.toml
- CHANGELOG.md
- ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs
- ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj
- ComAmazonawsDynamodb/runtimes/python/pyproject.toml
- ComAmazonawsKms/runtimes/net/AWS-KMS.csproj
- ComAmazonawsKms/runtimes/net/AssemblyInfo.cs
- ComAmazonawsKms/runtimes/python/pyproject.toml
- StandardLibrary/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/STD.csproj
- StandardLibrary/runtimes/python/pyproject.toml
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- project.properties
> chore(release): 1.7.2 [skip ci]

- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/CompleteVectors.dfy
- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/VectorsComposition/AllRequiredEncryptionContextCmm.dfy
> test: fix test vector required ec cmm construction

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs
- AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj
- AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml
- AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs
- AwsCryptographyPrimitives/runtimes/net/Crypto.csproj
- AwsCryptographyPrimitives/runtimes/python/pyproject.toml
- CHANGELOG.md
- ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs
- ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj
- ComAmazonawsDynamodb/runtimes/python/pyproject.toml
- ComAmazonawsKms/runtimes/net/AWS-KMS.csproj
- ComAmazonawsKms/runtimes/net/AssemblyInfo.cs
- ComAmazonawsKms/runtimes/python/pyproject.toml
- StandardLibrary/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/STD.csproj
- StandardLibrary/runtimes/python/pyproject.toml
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- project.properties
> chore(release): 1.7.3 [skip ci]

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml
- AwsCryptographyPrimitives/runtimes/python/pyproject.toml
- ComAmazonawsDynamodb/runtimes/python/pyproject.toml
- ComAmazonawsKms/runtimes/python/pyproject.toml
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- project.properties
> chore(CI): Allow local testing

- .github/workflows/check-files.yml
- .github/workflows/semantic_release.yml
- .github/workflows/todo-release.yml
> chore: update alias, add Ritvik

- .github/workflows/library_dafny_verification.yml
- .github/workflows/library_interop_tests.yml
- .github/workflows/library_java_tests.yml
- .github/workflows/library_net_tests.yml
- .github/workflows/library_python_tests.yml
- .github/workflows/sem_ver.yml
- .github/workflows/semantic_release.yml
> chore: bump macos from 12 to 13 in CI

- ComAmazonawsDynamodb/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/services/dynamodb/internaldafny/ToNative.java
- ComAmazonawsKms/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/services/kms/internaldafny/ToNative.java
> chore: re-polymorph to repair Java Opaque to Exception conversion

- AwsCryptographicMaterialProviders/runtimes/java/src/main/java/software/amazon/cryptography/internaldafny/StormTrackingCMC/StormTrackingCMC.java
> fix: return error on interrupted sleep

- .github/workflows/library_interop_tests.yml
- .github/workflows/library_rust_tests.yml
- .gitignore
- AwsCryptographicMaterialProviders/project.properties
- AwsCryptographyPrimitives/project.properties
- ComAmazonawsDynamodb/project.properties
- ComAmazonawsDynamodb/runtimes/rust/Cargo.toml
- ComAmazonawsKms/project.properties
- TestVectorsAwsCryptographicMaterialProviders/Makefile
- TestVectorsAwsCryptographicMaterialProviders/project.properties
- TestVectorsAwsCryptographicMaterialProviders/runtimes/rust/.gitignore
- TestVectorsAwsCryptographicMaterialProviders/runtimes/rust/Cargo.toml
- TestVectorsAwsCryptographicMaterialProviders/runtimes/rust/src/main.rs
- project.properties
> feat(Rust): Interop test vectors; bump Dafny to 4.9.0

- AwsCryptographicMaterialProviders/runtimes/rust/src/aes_kdf_ctr.rs
> chore: remove warning in Rust

- StandardLibrary/runtimes/python/pyproject.toml
- codebuild/release/release-prod.yml
> chore(release): Java prod release doesn't always check out main branch

- .github/workflows/library_interop_tests.yml
- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml
- AwsCryptographyPrimitives/runtimes/python/pyproject.toml
- ComAmazonawsDynamodb/runtimes/python/pyproject.toml
- ComAmazonawsKms/runtimes/python/pyproject.toml
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- project.properties
> chore: Enable local testing

- AwsCryptographicMaterialProviders/runtimes/rust/src/storm_tracker.rs
> chore: update Rust StormTracker for MaxTime

- AwsCryptographicMaterialProviders/runtimes/rust/src/storm_tracker.rs
- StandardLibrary/src/Sets.dfy
- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/WriteJsonManifests.dfy
> fix: SetToSequence should be a method, not a function

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/DescribeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationErrorRefinement.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy
- AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/AdminProvider.java
- AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/MutationExampleDecryptEncryptStrategy.java
- AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationExample.java
- AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationExampleDecryptEncryptStrategy.java
- AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationResumeExample.java
- AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java
- AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessOriginalInFlightTestDecryptEncrypt.java
- AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessTerminalInFlightTestDecryptEncrypt.java
> chore: error refinement improvements decrypt/encrypt strategy

- .github/workflows/check-files.yml
See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables for a list of GitHub environmental variables. 
> fix(GHW): check-files apply to PR, not to diff b/w HEAD and branch

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/Model/KeyStoreAdmin.smithy
- AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/KeyStoreAdminException.java
- AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/MutationConflictException.java
- AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/MutationFromException.java
- AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/MutationInvalidException.java
- AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/MutationToException.java
- AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/MutationVerificationException.java
- AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/UnexpectedStateException.java
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystoreadmin/errors.py
> docs: update documentation trait for keystore admin

- cfn/ESDK-Hierarchy-CI.yaml
1. Address CFN Drift
2. Add two new IAM Roles that can be assumed by CI to test limited KMS Access
> chore: CFN Updates

- AwsCryptographicMaterialProviders/runtimes/rust/src/aes_kdf_ctr.rs
> chore: delete unused code

- AwsCryptographicMaterialProviders/runtimes/rust/src/impl_add.rs
- AwsCryptographicMaterialProviders/runtimes/rust/src/lib.rs
- AwsCryptographicMaterialProviders/runtimes/rust/src/timer.rs
- StandardLibrary/runtimes/rust/src/lib.rs
- StandardLibrary/runtimes/rust/src/standard_library_externs.rs
> chore(rust-externs): Add copyright string

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/Model/KeyStoreAdmin.smithy
- AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/Mutations.java
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystoreadmin/models.py
> docs(KSA): clarify mutation behvior

- AwsCryptographicMaterialProviders/runtimes/net/tests/LocalCMC.Tests/LocalCMCTests.cs
- AwsCryptographicMaterialProviders/runtimes/rust/Cargo.toml
- AwsCryptographicMaterialProviders/runtimes/rust/tests/local_cmc_tests.rs
> chore(Rust): Add Rust multithreading test for LocalCMC

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/structures.smithy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/Model/KeyStore.smithy
> fix: remove @sensitive from smithy models

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/Model/KeyStore.smithy
> chore(Smithy): remove Smithy trait un-supported by Smithy-Dafny

- AwsCryptographicMaterialProviders/runtimes/rust/Cargo.toml
- AwsCryptographyPrimitives/runtimes/rust/Cargo.toml
- ComAmazonawsDynamodb/runtimes/rust/.gitignore
- ComAmazonawsDynamodb/runtimes/rust/Cargo.toml
- ComAmazonawsKms/runtimes/rust/.gitignore
- ComAmazonawsKms/runtimes/rust/Cargo.toml
- StandardLibrary/runtimes/rust/Cargo.toml
- TestVectorsAwsCryptographicMaterialProviders/runtimes/rust/Cargo.toml
> chore: update smithy-dafny

- AwsCryptographicMaterialProviders/runtimes/rust/src/dafny_libraries.rs
- StandardLibrary/runtimes/rust/src/dafny_libraries.rs
> fix: rust code used for testing must be allowed dead code

- .github/actions/polymorph_codegen/action.yml
- .github/workflows/library_codegen.yml
- AwsCryptographicMaterialProviders/runtimes/go/ImplementationFromDafny-go/awscryptographykeystoresmithygeneratedtypes/types.go
```
chore(CI): add CI to check git diff for polymorphed code in Go 
```
> chore(CI): add CI to check git diff for polymorphed code in Go 

- cfn/CI-Bot.yml
> fix: repo rename

- .github/workflows/library_java_tests.yml
> chore(CI): parallel java ci execution

- .github/workflows/pull.yml
> chore(CI): update required CI

- .github/workflows/library_codegen.yml
- .github/workflows/library_format.yml
> chore: ensure format checking is with dotnet 6

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsKeyring.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsMrkKeyring.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsRsaKeyring.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsUtils.dfy
> chore: fast fail for decrypt with keyid or alias

- .github/workflows/library_examples.yml
> fix(GHW): Library Example

- .releaserc.cjs
- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_materialproviders/models.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
> chore(java): set MPL version in build.gradle.kts from project.properties

- .github/actions/setup_dafny/action.yml
- .github/workflows/library_codegen.yml
- .github/workflows/library_dafny_verification.yml
- .github/workflows/library_format.yml
- .github/workflows/library_go_tests.yml
- .github/workflows/library_interop_tests.yml
- .github/workflows/library_java_tests.yml
- .github/workflows/library_net_tests.yml
- .github/workflows/library_python_tests.yml
- .github/workflows/library_rust_tests.yml
There is an issue with .NET and MacOS, this consolidates the building of Dafny into a single local action that we can manage.
> chore: re-enable Dafny

- .github/workflows/library_dafny_verification.yml
- .github/workflows/library_go_tests.yml
- .github/workflows/library_interop_tests.yml
- .github/workflows/library_java_tests.yml
- .github/workflows/library_net_tests.yml
- .github/workflows/library_python_tests.yml
- .github/workflows/library_rust_tests.yml
> chore: re-enable macOS CI

- TestVectorsAwsCryptographicMaterialProviders/dafny/KeyVectors/src/Index.dfy
- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/CompleteVectors.dfy
- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/JSONHelpers.dfy
- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/TestManifests.dfy
> chore: let fileio deal in uint8 instead of bv8

- AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs
- AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj
- AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/internaldafny/generated/dafny_src-py.dtr
- AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs
- AwsCryptographyPrimitives/runtimes/net/Crypto.csproj
- AwsCryptographyPrimitives/runtimes/python/pyproject.toml
- AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/internaldafny/generated/dafny_src-py.dtr
- CHANGELOG.md
- ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs
- ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj
- ComAmazonawsDynamodb/runtimes/python/pyproject.toml
- ComAmazonawsDynamodb/runtimes/python/src/aws_cryptography_internal_dynamodb/internaldafny/generated/dafny_src-py.dtr
- ComAmazonawsKms/runtimes/net/AWS-KMS.csproj
- ComAmazonawsKms/runtimes/net/AssemblyInfo.cs
- ComAmazonawsKms/runtimes/python/pyproject.toml
- ComAmazonawsKms/runtimes/python/src/aws_cryptography_internal_kms/internaldafny/generated/dafny_src-py.dtr
- StandardLibrary/runtimes/net/AssemblyInfo.cs
- StandardLibrary/runtimes/net/STD.csproj
- StandardLibrary/runtimes/python/pyproject.toml
- StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/generated/dafny_src-py.dtr
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/internaldafny/generated/dafny_src-py.dtr
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/internaldafny/generated/dafny_test-py.dtr
- project.properties
> chore: 1.10.0 [skip ci]

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/java/src/test/LocalCMCTests.java
- AwsCryptographicMaterialProviders/runtimes/java/src/test/MultiThreadedCMCTest.java
> chore(java): harden LocalCMCTests.java

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy
```
chore(bks): Add todo for test 
```
> chore(bks): Add todo for test 

- .github/PULL_REQUEST_TEMPLATE.md
Encourage us to specify the language of a commit by updating this template.
```
<message>
```
> chore: specify language in commits

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/CreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/Structure.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestCreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestVersionKey.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationStateStructures.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy
> chore(dafny): BranchKeyContext for HV-2

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/GetKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy
> chore(dafny): KS Refactor KeyStoreException

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestCreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestGetKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestAdminCreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestAdminHV1Only.dfy
> chore(dafny): Refactor GetKeys

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestGetKeys.dfy
> test(dafny): BKS Get Keys HV-1 and HV-2

- AwsCryptographicMaterialProviders/runtimes/rust/src/ecdh.rs
- AwsCryptographicMaterialProviders/runtimes/rust/src/ecdsa.rs
> chore: resolve rust warning

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestGetKeys.dfy
```
chore(dafny): Add helper function to VerifyGetKeys
```
> chore(dafny): Add helper function to VerifyGetKeys

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/CanonicalEncryptionContext.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/HierarchicalVersionUtils.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/Structure.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/CreateKeysHV2.dfy
I validated that the assume-axioms I added did not result in `assert false` passing.
```
```
> chore(dafny): BKSA Create Key verification with TODO

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy
> test(dafny): no touching the static branch-key-id in the dev branch

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy
> test(dafny): restore static test branch key id

- .github/workflows/duvet.yaml
```
chore: disable duvet
Duvet references in the code base are from spec reference
that has not been pushed to mutations/mutations.
For now, we will disable duvet, 
and re-enable it once mutations has been updated.
```
> chore: disable duvet

- AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/CreateKeyHv2Example.java
- AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java
1. Adds a simple java example to create HV-2 branch key
```
```
> chore(java): create key example for HV-2 branch key

- cfn/ESDK-Hierarchy-CI.yaml
> chore: Create KMS keys for HV1 & HV2 branch keys

- .github/workflows/library_interop_tests.yml
- .github/workflows/library_rust_tests.yml
- .github/workflows/nightly_dafny.yml
- .github/workflows/sem_ver.yml
- .github/workflows/semantic_release.yml
- AwsCryptographicMaterialProviders/runtimes/rust/Cargo.toml
- AwsCryptographyPrimitives/runtimes/rust/Cargo.toml
- ComAmazonawsDynamodb/runtimes/rust/Cargo.toml
- ComAmazonawsKms/runtimes/rust/Cargo.toml
- StandardLibrary/runtimes/rust/Cargo.toml
- TestVectorsAwsCryptographicMaterialProviders/runtimes/rust/Cargo.toml
> chore(rust): update smithy-dafny, use small-int feature

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KeyStoreAdminErrorMessages.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestAdminHV1Only.dfy
> test(dafny): BKSA errors if terminal HV is 1

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/DescribeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationStateStructures.dfy
> feat(dafny): BKSA Mutation Commitment includes HV

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/RawRSAKeyring.dfy
> chore(dafny): store privateKey in RawRSAKeyring because some Java code needs it

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/CreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestAdminCreateKeys.dfy
> chore(dafny): refactor VersionActiveBranchKey to  support multiple hierarchy versions

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestHvUtils.dfy
> test(dafny): KATs for Branch Key Context Digest

- .github/workflows/library_examples.yml
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/GetKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/HierarchicalVersionUtils.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/Structure.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/ApplyMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/AwsCryptographyKeyStoreAdminOperations.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/CommitmentAndIndex.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/DescribeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KeyStoreAdminErrorMessages.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KmsUtils.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationStateStructures.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/SystemKey/Handler.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestHierarchyVersion.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestMutateToHV2FromHV1.dfy
> chore(dafny): BKSA Mutate from HV-1 to HV-2 only Simple

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/AdminFixtures.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestMutationStateStructures.dfy
- Examples/java/src/main/java/software/amazon/cryptography/example/hierarchy/mutations/DescribeMutationExample.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/StaticMutation.java
> chore(dafny): BKSA Commitment pre-HV-2 static branch keys

- cfn/ESDK-Hierarchy-CI.yaml
> chore: CFN KMS GDK for HV-2

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/CleanupItems.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy
- Examples/java/src/main/java/software/amazon/cryptography/example/DdbHelper.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/concurrent/StorageVersionReadConcurrencyTests.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/concurrent/StorageWriteReadConcurrencyTests.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/DescribeMutationTest.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessOriginalInFlightTest.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessOriginalInFlightTestDecryptEncrypt.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessTerminalInFlightTest.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessTerminalInFlightTestDecryptEncrypt.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationSystemKeyKMSExample.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationSystemKeyTrustStorage.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationsSystemKeyKMSTamper.java
> chore: refactor helper methods for copy & delete branch keys

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/CreateKeysHV2.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KeyStoreAdminErrorMessages.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KmsUtils.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestMutateToHV2FromHV1.dfy
```
chore(dafny): WIP support encrypt decrypt 
```
> chore(dafny): support encrypt decrypt 

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy
- We will pick this up later. 
```
chore(dafny): Add TODO do support terminal hv-1 but not downgrading from hv-2 
```
> chore(dafny): Add TODO to support terminal hv-1 but not downgrading from hv-2 

- AwsCryptographicMaterialProviders/runtimes/rust/tests/local_cmc_tests.rs
```
chore(rust): remove print statements in Rust from testLotsOfAdding
```
> chore(rust): remove print statements from testLotsOfAdding 

- Examples/java/src/main/java/software/amazon/cryptography/example/hierarchy/mutations/MutationDecryptEncryptExample.java
- Examples/java/src/main/java/software/amazon/cryptography/example/hierarchy/mutations/MutationResumeExample.java
- Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java
```
chore(java): add decryptEncrypt examples 
```
> chore(java): add decryptEncrypt examples 

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/CreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy
> fix(dafny): BKS names

- StandardLibrary/src/MemoryMath.dfy
- StandardLibrary/src/UInt.dfy
- StandardLibrary/test/MemoryMath.dfy
> chore(dafny): support for memory size constraints

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/CreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy
> chore(dafny): add version on mutate functionality

- StandardLibrary/src/MemoryMath.dfy
- StandardLibrary/src/UInt.dfy
- StandardLibrary/test/MemoryMath.dfy
> chore(dafny): update UInt and MemoryMath as needed for DB-ESDK

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsKeyring.dfy
- SharedMakefileV2.mk
> chore(dafny): fix verification in kms keyring ondecrypt

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/CreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/GetKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy
- SharedMakefileV2.mk
> chore(dafny): add version key hv-2 proofs

- .github/workflows/library_codegen.yml
- .github/workflows/library_dafny_verification.yml
- .github/workflows/library_format.yml
- .github/workflows/library_interop_tests.yml
- .github/workflows/library_java_tests.yml
- .github/workflows/library_net_tests.yml
> chore: install polymorph dependencies in github workflows

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsKeyring.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/HierarchicalVersionUtils.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KeyStoreErrorMessages.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/Model/KeyStoreAdmin.smithy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/AwsCryptographyKeyStoreAdminOperations.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KeyStoreAdminErrorMessages.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestHierarchyVersion.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestAdminHV1Only.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestHv2KmsExceptions.dfy
remove redundant todos and resolved some quicker ones.
```
```
> chore(dafny): cleanup todos in hv-2 

- StandardLibrary/runtimes/go/ImplementationFromDafny-go/DafnyLibraries/externs.go
> chore(go): implement missing MutableMap::content()

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/CreateKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/GetKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/HierarchicalVersionUtils.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KeyStoreErrorMessages.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestGetKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestLyingBranchKey.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestHierarchyVersion.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestMutateLyingBranchKeys.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestMutationHappyPath.dfy
- Adding failure whenever encountering un-expected attribute 
```
chore(dafny): add failure for un-expected attribute 
```
> chore(dafny): add failure for unexpected attribute in EC on HV-2

- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/HierarchicalVersionUtils.dfy
- AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestHierarchicalVersionUtils.dfy
> test(dafny): some testing on EC transforms

- AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsKeyring.dfy
> chore(dafny): remove duplicate proof in kms keyring

- StandardLibrary/runtimes/go/ImplementationFromDafny-go/DafnyLibraries/externs.go
- cfn/ESDK-Hierarchy-CI.yaml
> chore: CFN for Restricted EC

- cfn/ESDK-Hierarchy-CI.yaml
Go to ESDK-Hierarchy-CI cloud formation stack and the change set for it is `ESDK-Hiera-d0tndix1f3-zpir1nrv0c`
```
chore: add MPL CI to principal of KmsKeyForRobbieOnly
```
> chore: add MPL CI to principal of KmsKeyForRobbieOnly 

- cfn/ESDK-Hierarchy-CI.yaml
> chore: CFN for two new roles to prove prefixing/defixing behavior

- StandardLibrary/src/String.dfy
> chore(dafny): Make HasSubString generic

- AwsCryptographyPrimitives/runtimes/python/pyproject.toml
> chore(deps): Extend supported pyca version range

- CHANGELOG.md
```
chore: update changelog to add python for 1.11.0
```
> chore: update changelog to add python for 1.11.0

- .github/workflows/duvet.yaml
- .github/workflows/library_examples.yml
- .github/workflows/library_interop_tests.yml
- .github/workflows/pull.yml
- .github/workflows/push.yml
- AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystoreadmin/client.py
- Disable Duvet
- Disable Python Tests
- Disable .NET Tests
- Only have inter-opt testing b/w Java and .NET
- Re-polymorph Python
- Fix library_examples.yml set up actions
```
chore: update CI for 1.11.0 release
```
> chore: update CI for 1.11.0 release

- .github/workflows/library_interop_tests.yml
> chore: bump credentials to 2 hours, for python

- AwsCryptographicMaterialProviders/runtimes/java/README.md
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/fuzz_generator.py
- created a new fuzzing test script that will be the foundation of this project (currently contains only encryptionContext-related-attributes fuzzing
- removed description (errorDescription, keyDescription) fuzzing to save compute time
- randomized keyring type selection (previous was set to positive keyring for only KMS keys)
- dealing with deprecated function from hypothesis
- modular key name/namespace fuzzing
> feat(python): create new fuzz generation script.

- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/fuzz_generator.py
fixed blocking comments and few more strategies to encryption context fuzzing.
> fix(python): fix blocking comments, add more strategies for encryption context fuzzing.

- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/fuzz_generator.py
- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/keys.json
Added changes to keep track of work to complete moving forward. Search up `TODO-Fuzztesting` in fuzz_generator.py to locate WIP.
> fix(python): add TODOs for tracking work moving forward

- TestVectorsAwsCryptographicMaterialProviders/runtimes/python/fuzz_generator.py
##Changes
Added fuzz_key_identifiers, an important TODO-Fuzztesting
> chore(python): add key fuzzing capabilities

- AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml
- AwsCryptographyPrimitives/runtimes/python/pyproject.toml
- CHANGELOG.md
- ComAmazonawsDynamodb/runtimes/python/pyproject.toml
- ComAmazonawsKms/runtimes/python/pyproject.toml
- TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
> chore: allow local testing

- StandardLibrary/src/String.dfy
- StandardLibrary/test/TestString.dfy
> chore(dafny): add search and replace methods

- .github/workflows/daily_ci.yml
```
chore(CI): update slack notification to include link of GHA run 
```
> chore(CI): update slack notification to include link of GHA run 

- .github/workflows/daily_ci.yml
- .github/workflows/pull.yml
- TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/test/fuzz_generator.py
- PR CI and Daily CI
- self review
- Quip Doc of Fuzz-testing (will include TODOs there)
- removing TODOs from Script
```
```
> chore(python): fuzz pr ci and daily ci

- AwsCryptographicMaterialProviders/runtimes/python/test/internaldafny/test_i_keystore_exceptions.py
- StandardLibrary/src/String.dfy
- StandardLibrary/test/TestString.dfy
> chore(dafny): add new SearchAndReplaceWhole and friends

- AwsCryptographicMaterialProviders/runtimes/rust/src/dafny_libraries.rs
> chore(rust): note unused parameter

- .github/actions/setup_dafny/action.yml
> chore(dafny): bump setup_dafny

- AwsCryptographicMaterialProviders/runtimes/rust/src/kms.rs
- ComAmazonawsKms/runtimes/rust/src/kms.rs
> chore: update kms externs correctly

- .github/workflows/library_interop_tests.yml
- project.properties
> chore(rust): bump dafny version for rust to 4.10
