AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/KeyWrapping/EdkWrapping.dfy
*Issue #, if available:* https://github.com/aws/aws-cryptographic-material-providers-library-java/issues/144
*Description of changes:* Fixes the error message, the validation for encryption materials happens during encryption (`OnEncrypt`) and so the error message MUST refer to (invalid) _encryption_ materials. 
*Squash/merge commit message, if applicable:*
=> fix: fix typo in encryption materials validation

.github/workflows/library_net_tests.yml, SharedMakefileV2.mk
The .Net framework is only supported
in windows.
Also, update the SharedMakefile
to consolidate passing the framework.
=> chore: Update CI for .Net Framework

.github/workflows/library_dafny_verification.yml, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsMrkKeyring.dfy, SharedMakefileV2.mk, StandardLibrary/src/Base64.dfy, StandardLibrary/src/Base64Lemmas.dfy
The Dafny process does not
parallelize very well.
The vcsCores option controls
the number of Z3 processes,
not the number of processes handling parsing.
As such the MPL spends a long time
chewing processing files.
Breaking this up is less efficient,
but may be faster.
=> chore: Verify by file

AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/MultiKeyring.dfy
By returning the underlying error,
customers can more clearly see
why the generator failed.
This is especially important for the KMSRsa keyring.
Because it does not support signature suites.
=> fix: Forward the underlying error

.github/workflows/library_format.yml, .github/workflows/manual.yml, .github/workflows/pull.yml, .github/workflows/push.yml, AwsCryptographicMaterialProviders/Makefile, AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographyPrimitives/runtimes/java/build.gradle.kts, ComAmazonawsDynamodb/runtimes/java/build.gradle.kts, ComAmazonawsKms/runtimes/java/build.gradle.kts, Makefile, SharedMakefileV2.mk, StandardLibrary/runtimes/java/build.gradle.kts, TestVectorsAwsCryptographicMaterialProviders/Makefile, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
* Update the root Makefile to run for each library
* Add format and codegen targets to root Makefile
* Add java and net format/check targets
* Update format action to prepare for update
=> chore: Consolidate tasks

AwsCryptographicMaterialProviders/codebuild/release-prod.yml, AwsCryptographicMaterialProviders/codebuild/release-staging.yml, AwsCryptographicMaterialProviders/codebuild/sign.yml, AwsCryptographicMaterialProviders/codebuild/test-prod.yml, AwsCryptographyPrimitives/codebuild/release-prod.yml, AwsCryptographyPrimitives/codebuild/release-staging.yml, AwsCryptographyPrimitives/codebuild/sign.yml, AwsCryptographyPrimitives/codebuild/test-prod.yml, ComAmazonawsDynamodb/codebuild/release-prod.yml, ComAmazonawsDynamodb/codebuild/release-staging.yml, ComAmazonawsDynamodb/codebuild/sign.yml, ComAmazonawsDynamodb/codebuild/test-prod.yml, ComAmazonawsKms/codebuild/release-prod.yml, ComAmazonawsKms/codebuild/release-staging.yml, ComAmazonawsKms/codebuild/sign.yml, ComAmazonawsKms/codebuild/test-prod.yml, StandardLibrary/codebuild/release-prod.yml, StandardLibrary/codebuild/release-staging.yml, StandardLibrary/codebuild/sign.yml, StandardLibrary/codebuild/test-prod.yml, codebuild/release/release-prod.yml, codebuild/release/validate-release.yml, codebuild/staging/release-staging.yml, codebuild/staging/validate-staging.yml
CI and release processes use the same
single source of truth for Dafny version
=> chore: Use project.properties for Dafny version in release

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographyPrimitives/runtimes/java/build.gradle.kts, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, ComAmazonawsDynamodb/runtimes/java/build.gradle.kts, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsKms/runtimes/java/build.gradle.kts, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, StandardLibrary/runtimes/java/build.gradle.kts, StandardLibrary/runtimes/net/STD.csproj, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, TestVectorsAwsCryptographicMaterialProviders/runtimes/net/TestVectors.csproj, project.properties
Java and DotNet runtimes get their Dafny version
from the same location as CI and release scripts
=> chore: Runtimes get dafny from project properties

TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- Remove `software.amazon.awssdk:core:2.19.1` dependency from TestVectors `build.gradle` to sync with `AwsCryptographicMaterialProviders` `build.gradle`. 
- The above dependency prevents the ESDK-Java `pom.xml` from pulling MPL TestVector.
=> chore(Java): resolve `awssdk:core` dependency in TestVectors build.gradle.kts

ComAmazonawsKms/runtimes/java/src/main/java/software/amazon/cryptography/services/kms/internaldafny/__default.java, ComAmazonawsKms/runtimes/net/Extern/KMSClient.cs, ComAmazonawsKms/test/TestComAmazonawsKms.dfy
The ESDK will pass an empty string
as the AWS region in cases where no region is know.
In this case we defer to the SDK
on how to evaluate the default region.
=> fix: Empty string defers to SDK default region

StandardLibrary/src/Sets.dfy, StandardLibrary/src/Sorting.dfy, StandardLibrary/src/StandardLibrary.dfy
A bug in Dafny meant these were erroneously unchecked before. Now they're required (as they always should have been).
Some of the changes are in the `libraries` repository, so this commit updates that submodule, as well.
=> chore: Add missing (!new) type characteristics

.github/workflows/ci_static-analysis.yaml, .github/workflows/dafny_version.yaml, .github/workflows/duvet.yaml, .github/workflows/library_dafny_verification.yml, .github/workflows/library_format.yml, .github/workflows/library_java_tests.yml, .github/workflows/library_net_tests.yml
Closes: #32 , #38 , #136 , #137 , 
=> chore(deps): bump GitHub Action Dependencies

.github/workflows/sem_ver.yml, .github/workflows/semantic_release.yml, .releaserc.cjs
=> chore(GHA): add semantic release manual gha

cfn/ESDK-Hierarchy-CI.yaml
Move Private[ ESDK Dafny's CI yaml to this Repo](https://github.com/aws/private-aws-encryption-sdk-dafny-staging/blob/v4-seperate-modules/cfn/CI.yaml)
since it defines the DDB Table and KMS Keys several Repos have been using 
to test the H-Keyring,
and this template is only on a now dead branch.
Add another normal KMS Key to it.
```
chore(CFN): add another KMS Key ARN for Key Store Testing
```
I will deploy to the correct account once approved but before merging.
=> chore(CFN): add another KMS Key ARN for Key Store Testing

AwsCryptographicMaterialProviders/project.properties, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/MultiThreadedCache.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/PutCacheEntryInput.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/SingleThreadedCache.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/StormTrackingCache.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/TypeConversion.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographyKeyStore/TypeConversion.cs, AwsCryptographyPrimitives/project.properties, AwsCryptographyPrimitives/runtimes/net/Generated/TypeConversion.cs, ComAmazonawsDynamodb/project.properties, ComAmazonawsDynamodb/runtimes/net/Generated/TypeConversion.cs, ComAmazonawsKms/project.properties, ComAmazonawsKms/runtimes/net/Generated/TypeConversion.cs, TestVectorsAwsCryptographicMaterialProviders/project.properties, TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/KeyVectors/TypeConversion.cs, TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/TestVectorsAwsCryptographicMaterialProviders/AwsCryptographicMaterialProvidersShim.cs, TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/TestVectorsAwsCryptographicMaterialProviders/TypeConversion.cs
=> feat: repolymorph to get dotnet constraint checking

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/Model/AwsCryptographyKeyStoreTypes.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/Model/KeyStore.smithy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/AwsCryptographyKeyStoreOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/ToDafny.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/ToNative.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/model/GetKeyStoreInfoOutput.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/model/KMSConfiguration.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/model/KeyStoreConfig.java, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographyKeyStore/KMSConfiguration.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographyKeyStore/TypeConversion.cs
_Issue #, if available:_ 
1. Replace  `mrkKmsKeyArn` with  `kmsMRKeyArn`, as MRK means Multi-Region Key, so "mrkKMSKey" is a little redundant 
2. JavaDocs to describe the behavioral difference of the two KMS Configurations
```
fix(KeyStore): JavaDocs for KMS Configuration
```
=> fix(KeyStore): JavaDocs for KMS Configuration

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
* **dafny:** Local Service Constructors MUST return concrete ([64f72c1](https://github.com/aws/aws-cryptographic-material-providers-library/commit/64f72c121fef31a83bcf3a5346d7efc1e84ab25f))
* Improvements to the Java Release process ([#162](https://github.com/aws/aws-cryptographic-material-providers-library/issues/162)) ([d92c06a](https://github.com/aws/aws-cryptographic-material-providers-library/commit/d92c06a2fd355290f27df669c866157e14da9793))
* Increase try-block scope when calling MPL components ([#267](https://github.com/aws/aws-cryptographic-material-providers-library/issues/267)) ([7661bf4](https://github.com/aws/aws-cryptographic-material-providers-library/commit/7661bf4b0f23e810f825fd884ecdc036b5e472d5))
* Multi-Region Key Logic in the Keystore …
=> chore(release): 1.3.0

.github/workflows/manual.yml, .github/workflows/nightly_dafny.yml
Automates cutting an issue to `dafny-lang/dafny` if the nightly build against the latest Dafny prerelease fails.
Reuses the same GH token as the semantic release workflows, since that already has more than enough permissions (only `public_repo` is needed for this action).
Tested this by putting the same steps in the manual CI workflow, which created this issue: https://github.com/dafny-lang/dafny/issues/5391
=> ci: Cut Dafny issues on nightly failures

AwsCryptographyPrimitives/runtimes/java/src/main/java/Digest_Compile/ExternDigest.java, AwsCryptographyPrimitives/runtimes/java/src/main/java/Signature/ECDSA.java, AwsCryptographyPrimitives/runtimes/java/src/main/java/Signature/PrivateKeyUtils.java, AwsCryptographyPrimitives/runtimes/java/src/main/java/Signature/PublicKeyUtils.java, AwsCryptographyPrimitives/runtimes/java/src/main/java/Signature/SignatureAlgorithm.java, StandardLibrary/runtimes/java/src/main/java/StandardLibraryInternal/InternalResult.java
This internal helper class was defined in the wrong place, which makes it look strange to use it outside of the MPL.
=> chore: Move InternalResult into StandardLibrary(Internal)

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
- **Keystore:** Introduce additional KMSConfiguration options ([#316](https://github.com/aws/aws-cryptographic-material-providers-library/issues/316)) ([f3a0a52](https://github.com/aws/aws-cryptographic-material-providers-library/commit/f3a0a5269e611afd254425226d32eaaed1f3d99b))
The Hierarchical Keyring's Keystore now supports four (4) `KMSConfigurations`:
- kmsKeyArn
- kmsMRKeyArn
- discovery
- mrDiscovery
See our [JavaDocs](https://aws.github.io/aws-cryptographic-material-providers-library/index.html?software/amazon/cryptography/keystore/model/KMSConfiguration.html) for details on how these options effect the relationship between a Keystore and KMS.
- .NET : Bump dependency [BouncyCastle.Cryptography](https://github.com/bcgit/bc-csharp) from 2.2.1 to 2.3.1. …
=> chore(release): 1.4.0

.releaserc.cjs
During last MPL release, 
Semantic Release failed to bump the TestVectors in Java,
and I did it manually.
This should fix that.
`chore: add Java TestVectors to Semantic Release script`
=> chore: add Java TestVectors to Semantic Release script

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestVersionKey.dfy
=> chore: spec and test for ARN unchanged in VersionKey

.github/workflows/dafny_verify_version.yaml, .github/workflows/daily_ci.yml, .github/workflows/pull.yml, .github/workflows/push.yml, project.properties
=> chore: verify with 4.6

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestLyingBranchKey.dfy, cfn/lyingBranchKeyCreation.md
The Keystore's threat model protects against malicious actors with write access to the backing Keystore Table.
In particular, the Keystore's implementation assures that a Branch Key's DynamoDB Item correctly describes the KMS ARN used to Generate the Branch Key Materials.
This additional test validates this mitigation.
This is an additional, explicit, test of this already existing behavior/mitigation.
```
test(Keystore): assert that lying branch keys are rejected
```
=> test(Keystore): assert that lying branch keys are rejected

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, CHANGELOG.md, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts
* **MPL:** Add Raw ECDH and AWS KMS ECDH Keyrings ([#419](https://github.com/aws/aws-cryptographic-material-providers-library/issues/419)) ([0946a7e](https://github.com/aws/aws-cryptographic-material-providers-library/commit/0946a7ed801a6269565651cfe2ef17831d89d99c))
=> chore(release): 1.5.0

cfn/CI.yaml
=> chore: add ecdh cfn policy

AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/test/TestEcdhCalculation.dfy, AwsCryptographyPrimitives/runtimes/java/src/main/java/ECDH/DeriveSharedSecret.java, AwsCryptographyPrimitives/runtimes/net/Extern/ECDH.cs, TestVectorsAwsCryptographicMaterialProviders/dafny/KeyVectors/Model/AwsCryptographyMaterialProvidersTestVectorKeysTypes.dfy, TestVectorsAwsCryptographicMaterialProviders/dafny/KeyVectors/Model/key-vectors.smithy, TestVectorsAwsCryptographicMaterialProviders/dafny/KeyVectors/src/KeyDescription.dfy, TestVectorsAwsCryptographicMaterialProviders/dafny/KeyVectors/src/KeyMaterial.dfy, TestVectorsAwsCryptographicMaterialProviders/dafny/KeyVectors/src/KeyringFromKeyDescription.dfy, TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/VectorsComposition/AllKmsEcdh.dfy, TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/VectorsComposition/AllRawECDH.dfy, TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/test/keys.json, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviderstestvectorkeys/ToDafny.java, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviderstestvectorkeys/ToNative.java, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviderstestvectorkeys/model/KmsEcdhKeyring.java, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviderstestvectorkeys/model/RawEcdh.java, TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/KeyVectors/KmsEcdhKeyring.cs, TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/KeyVectors/RawEcdh.cs, TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/KeyVectors/TypeConversion.cs
Adds comments to ecdh extern regarding signed/unsigned representation.
Updates test vectors to include raw base64 der encoded public keys, to facilitate java/net interop testing of der public keys.
=> chore: speed up ecdh test vectors to no call KMS on creation

.github/workflows/todo-java-release.yml, .github/workflows/todo-release.yml, cfn/CB.yml, codebuild/release/release-prod.yml
_Issue #, if available:_ Sonatype requires User Token
As of Friday 6/21, Sonatype requires maven releases to use token-based authentication, instead of username and password authentication.
- Use Sonatype token-based authentication to publish to Maven
- Rename WIP GitHub Workflows to release, to make it clear they are not used to release, but ideally would be used in the future.
```
chore(Java): Sonatype requires User Token
```
=> chore(Java): Sonatype requires User Token

AwsCryptographyPrimitives/test/TestECDH.dfy, project.properties
=> chore: bump dafnyVerifyVersion to 4.7.0

.github/workflows/check_only_keyword.yml, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsEcdhKeyring.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/RawECDHKeyring.dfy
=> chore(verfication): remove {:only}

StandardLibrary/runtimes/python/src/standard_library/internaldafny/extern/ConcurrentCall.py, StandardLibrary/runtimes/python/src/standard_library/internaldafny/extern/DafnyLibraries.py, StandardLibrary/runtimes/python/src/standard_library/internaldafny/extern/SortedSets.py, StandardLibrary/runtimes/python/src/standard_library/internaldafny/extern/Time.py, StandardLibrary/runtimes/python/src/standard_library/internaldafny/extern/UTF8.py, StandardLibrary/runtimes/python/src/standard_library/internaldafny/extern/UUID.py, StandardLibrary/runtimes/python/src/standard_library/internaldafny/extern/__init__.py
=> Python: StandardLibrary Externs

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/AwsCryptographyKeyStoreOperations.dfy, StandardLibrary/runtimes/java/src/main/java/Time/__default.java, StandardLibrary/src/Time.dfy, StandardLibrary/test/Time.dfy
The Java extern returned `YYYY-MM-DDTHH:mm:ss:ssssssZ` This is not ISO8601.
Also, time is non-deterministic,
therefore GetCurrentTimeStamp MUST be a method.
=> fix: GetCurrentTimeStamp returns ISO8601 format

AwsCryptographyPrimitives/src/Digest.dfy, AwsCryptographyPrimitives/src/ECDH.dfy, AwsCryptographyPrimitives/src/Signature.dfy
=> chore: add documentation to externs

AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/CMMs/DefaultCMM.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/CMMs/RequiredEncryptionContextCMM.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/CanonicalEncryptionContext.dfy, AwsCryptographyPrimitives/test/TestRSA.dfy, StandardLibrary/src/StandardLibrary.dfy
Removes uses of `:|` in Dafny code, and updates the libraries submodule to a version that does not use it, either. This will eliminate failures when compiling with Dafny 4.8.0 and `-definiteAssignment:3`.
=> fix: Remove uses of `:|`

TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/test/RunMain.dfy
=> fix: maintain order in test vectors for languages with parallel tests

TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/TestVectors.dfy
=> chore: improve message for failed test vector test

Makefile, StandardLibrary/src/GetOpt.dfy, TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/Index.dfy
=> fix: test vector help text

StandardLibrary/test/TestComputeSetToOrderedSequenceCharLess.dfy
=> test(StandardLibrary): Update Unicode tests to work around Dafny transpile bug

.releaserc.cjs, AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, project.properties
* add ECDH error message for Rust ([#574](https://github.com/aws/aws-cryptographic-material-providers-library/issues/574)) ([473a34a](https://github.com/aws/aws-cryptographic-material-providers-library/commit/473a34abe688629e1a5b8abe8bc859e1128ea40b))
* **DDB-Model:** DDB Supports 100 actions per Transaction ([#692](https://github.com/aws/aws-cryptographic-material-providers-library/issues/692)) ([8a67843](https://github.com/aws/aws-cryptographic-material-providers-library/commit/8a6784372ff635828aa15b9edd7a1c7a37a95286))
* GetCurrentTimeStamp returns ISO8601 format ([#575](https://github.com/aws/aws-cryptographic-material-providers-library/issues/575)) ([c07a51f](https://github.com/aws/aws-cryptographic-material-providers-library/commit/c07a51fc29ff70411f7573bca96d2a091db8c1ed))
* …
=> chore(release): 1.6.0

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/AdminProvider.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/CreateKeyExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/MutationExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/ApplyMutationOutput.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/TestUtils.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/MutationExampleTests.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/StorageCheater.java
=> chore(Java): Examples for Mutations

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/DefaultKeyStorageInterface.dfy
This resolves feedback from both @seebees  and @josecorella 
on Mutations branch.
Verification failure is due to (just like in #751 ):
1. Key Store Admin's Index.dfy not proving Fresh, which has been a long standing issue with the Admin
2. In `AwsCryptographyKeyStore/test/Storage/TestGetItemsForInitializeMutation.dfy`, the test assumes `type` is in the Encryption Context. It is, but Structure.dfy does not prove that, so it must be proven else where.
A .NET MPL job failed due to .NET 48 Sig V4 Auth bug.
=> refactor(Storage): Use TransactGet instead of BatchGet for GetInitMut

AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/AwsCryptographyMaterialProvidersTypes.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/cryptographic-materials-cache.smithy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/keyrings.smithy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/AwsCryptographyMaterialProvidersOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/CMCs/CacheConstants.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsHierarchicalKeyring.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/test/Keyrings/AwsKms/AwsKmsHierarchicalKeyring/TestAwsKmsHierarchicalKeyring.dfy, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviders/ToDafny.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviders/ToNative.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviders/model/CacheType.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviders/model/CreateAwsKmsHierarchicalKeyringInput.java, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/CacheType.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/CreateAwsKmsHierarchicalKeyringInput.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographicMaterialProviders/TypeConversion.cs, TestVectorsAwsCryptographicMaterialProviders/dafny/KeyVectors/src/CreateStaticKeyStores.dfy, TestVectorsAwsCryptographicMaterialProviders/dafny/KeyVectors/src/KeyringFromKeyDescription.dfy, TestVectorsAwsCryptographicMaterialProviders/runtimes/net/Generated/TestVectorsAwsCryptographicMaterialProviders/TypeConversion.cs
Duvet is expected to fail.
Adding a new type `Shared` to the union `CacheType` in order to allow a shared cache across multiple hierarchy keyrings. The customer will provide an already initialized `CryptographicMaterialsCache` as an `Shared` type, which can be shared across multiple Hierarchical Keyrings. 
As before, if any other type in CacheType is provided to the Hierarchical Keyring, it will initialize a cache of that type, to be used with only that Hierarchical Keyring. If nothing is provided here, a DefaultCache is initialized to be used with only that Hierarchical Keyring with entryCapacity = 1000.")
If the method `CreateCryptographicMaterialsCache` is called with this `Shared` `ICryptographicMaterialsCache` type as input, it MUST …
=> feat(HierarchyKeyring; CMC): Shared cache across Hierarchy Keyrings

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/DefaultKeyStorageInterface.dfy, AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/CredentialUtils.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/AdminProvider.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/CreateKeyExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/Fixtures.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/MutationKmsAccessInFlightTest.java
I will merge this after I give @josecorella  a chance to see if #751 addresses other concerns.
Verification failure is due to:
1. Key Store Admin's Index.dfy not proving Fresh, which has been a long standing issue with the Admin
2. In `AwsCryptographyKeyStore/test/Storage/TestGetItemsForInitializeMutation.dfy`, the test assumes `type` is in the Encryption Context. It is, but Structure.dfy does not prove that, so it must be proven else where.
A Dotnet DDB Test failed due to throttling from Nuget.
=> test(Mutations): additional testing for Mutations

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/DefaultKeyStorageInterface.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/Structure.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Storage/TestGetItemsForInitializeMutation.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationStateStructures.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy, AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/CredentialUtils.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/AdminProvider.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/CreateKeyExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/Fixtures.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/MutationKmsAccessInFlightTest.java
Responding to @josecorella comments on #720 .
Verification failure is due to:
1. Key Store Admin's Index.dfy not proving Fresh, which has been a long standing issue with the Admin
2. In `AwsCryptographyKeyStore/test/Storage/TestGetItemsForInitializeMutation.dfy`, the test assumes `type` is in the Encryption Context. It is, but Structure.dfy does not prove that, so it must be proven else where.
=> chore(Mutations): respond to comments on PR #720

AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/AwsCryptographyMaterialProvidersOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsHierarchicalKeyring.dfy, AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, project.properties
This is a merge from main.
```
git checkout rc-1.7.0 --recurse-submodules
git merge main --no-commit
git checkout -b tony/rc-1.7.0-merge-main
git commit 
```
CI Failure on Mac OS .NET 6.0 ([dd6fea5](https://github.com/aws/aws-cryptographic-material-providers-library/pull/786/commits/dd6fea5c83d8931a42cbff34589ca5049c8a9fd3)):
```
TestGetItemsForInitializeMutation.TestHappyCase: FAILED
dafny/AwsCryptographyKeyStore/test/Storage/TestGetItemsForInitializeMutation.dfy(30,18): Wrappers.Result.Failure(AwsCryptographyKeyStoreTypes.Error.KeyStorageException(DDB through an exception for GetItemsForInitializeMutation's TransactGetItems. Table Name: KeyStoreDdbTable	Branch Key ID: 75789115-1deb-4fe3-a2ec-be9e885d1945	DDB Message: Transaction cancelled, please refer cancellation reasons for specific …
```
=> chore: Merge main

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/Model/AwsCryptographyKeyStoreTypes.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/Model/KeyStore.smithy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestConfig.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestGetKeys.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationErrorRefinement.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/ToDafny.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/ToNative.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/model/KeyManagementException.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/MutationKmsAccessInFlightTest.java, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographyKeyStore/KeyManagementException.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographyKeyStore/TypeConversion.cs
If the KMS Call, for mutating the Beacon, fails,
it MAY indicate the MPL Consumer does not have access to the terminal KMS Key.
If the KMS call for verifying a terminal version fails, it MAY indicate the MPL Consumer does not have access to the terminal KMS Key.
`feat(Mutations-TODO): Some Terminal KMS Exceptions`
=> feat(Mutations-TODO): Some Terminal KMS Exceptions

AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_keystore/config.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/config.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/errors.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_materialproviders/smithygenerated/aws_cryptography_materialproviders/models.py, AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/config.py, AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/models.py, ComAmazonawsDynamodb/runtimes/python/src/aws_cryptography_internal_dynamodb/smithygenerated/com_amazonaws_dynamodb/shim.py, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/config.py, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/smithygenerated/aws_cryptography_materialproviderstestvectorkeys/errors.py
I won't merge this until the related Smithy-Dafny changes land on main.
Repolymorph with:
* Orphaned shapes
* Updated Config shape generation
* Updated BaseClient typehint generation
=> fix(Python): Repolymorph to add orphaned shapes

AwsCryptographicMaterialProviders/codebuild/release-python/prod-release.yml, AwsCryptographicMaterialProviders/codebuild/release-python/test-release.yml, AwsCryptographyPrimitives/codebuild/release-python/prod-release.yml, AwsCryptographyPrimitives/codebuild/release-python/test-release.yml, ComAmazonawsDynamodb/codebuild/release-python/prod-release.yml, ComAmazonawsDynamodb/codebuild/release-python/test-release.yml, ComAmazonawsKms/codebuild/release-python/prod-release.yml, ComAmazonawsKms/codebuild/release-python/test-release.yml, StandardLibrary/codebuild/release-python/prod-release.yml, StandardLibrary/codebuild/release-python/test-release.yml
Python fetches source code from within the buildspec.
For the MPL, `$COMMIT_ID` will often be a git tag.
Python will need to fetch the tags.
This isn't needed for Java/NET.
Both use `--source-version XX` in their CodeBuild config, which accepts a git tag by default.
=> chore(Python): Fetch tags as part of release

AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsHierarchicalKeyring.dfy
The Model for the CMC is a little unclear,
but it could be interrupted to indicate that a 
put to the cache for an item that already exists can
throw an `EntryAlreadyExists` error.
The H-Keyring should ignore such an exception.
`fix(H-Keyring): if putCache throws EntryAlreadyExists, ignore`
=> fix(H-Keyring): if putCache throws EntryAlreadyExists, ignore

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, ComAmazonawsKms/runtimes/python/pyproject.toml, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, StandardLibrary/runtimes/python/pyproject.toml, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/internaldafny/generated/dafny_test-py.dtr, project.properties
---
This release is available in the following languages:
- Python
* **H-Keyring:** if getCache returns Error not EntryDoesNotExist, error ([#846](https://github.com/aws/aws-cryptographic-material-providers-library/issues/846)) ([3413fcb](https://github.com/aws/aws-cryptographic-material-providers-library/commit/3413fcbc889e2c31fb753ff3eca852c1d5db1140))
* H-Keyring: if putCache throws EntryAlreadyExists, swallow ([#856](https://github.com/aws/aws-cryptographic-material-providers-library/issues/856)) ([d01a182](https://github.com/aws/aws-cryptographic-material-providers-library/commit/d01a182b5e62010f44616dacd6730aa873dec4c7))
* **Python:** Repolymorph to add orphaned shapes ([#831](https://github.com/aws/aws-cryptographic-material-providers-library/issues/831)) …
=> chore(release): 1.7.1 [skip ci]

AwsCryptographyPrimitives/runtimes/java/src/main/java/HMAC/HMac.java, AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/internaldafny/extern/HMAC.py, AwsCryptographyPrimitives/src/HKDF/HMAC.dfy
I added these as a migration workaround for upgrading the Dafny version, but as a side effect it made `HMac` a mixed Dafny/native class when it wasn't intended to be, and this isn't supported on all target languages (e.g. Go). Easy fix to move them out of the class to the surrounding module instead.
=> fix: Move Java helper methods out of extern class

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/DDBKeystoreOperations.dfy
https://t.corp.amazon.com/V1528740765
The variable name `ConditionExpression` and the type `ConditionExpression` ends up colliding in Go. This PR uses cameCase for the variable name to avoid collision.
=> fix: variable name collision fix for Go

AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/AwsKmsUtils.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/Keyrings/AwsKms/Constants.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/test/TestEcdhCalculation.dfy, AwsCryptographyPrimitives/test/TestRSA.dfy, SharedMakefileV2.mk
Remove all Dafny warnings and set warnings to error.
By removing all the errors, `--allow-warnings` can be removed from verification. This means that any verification warning will now fail the build. This is especially relevant if `{:only}` is ever committed. See #517. This would now cause CI verification to fail.
=> chore: Remove Dafny warnings

AwsCryptographicMaterialProviders/runtimes/python/README.rst, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/python/test/functional/test_ECDH_exceptions.py, AwsCryptographyPrimitives/test/TestECDH.dfy, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/python/pyproject.toml, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/pyproject.toml
* Bump minimum versions of `pyca` and `boto3` to the current minimum releases.
* Update expected ECDH exception messages from `pyca` bump 
=> chore(deps-Python): bump boto3 and cryptography versions

.github/workflows/nightly_dafny.yml
Fixes startup failures like https://github.com/aws/aws-cryptographic-material-providers-library/actions/runs/11389253918
The `getVersion` job definition is copied from https://github.com/aws/aws-cryptographic-material-providers-library/blob/787f63a4cae67d9079b28c190a7c3d70854f9d67/.github/workflows/daily_ci.yml#L9-L12
=> ci: fix missing getVersion in nightly Dafny CI

StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/extern/Time.py
=> fix: python time externs should return integers

.releaserc.cjs
Before, Python releases would pin to minor versions.
This is not in parity with Java/.NET, which pin to patch versions.
Let's bias for keeping language release behavior in parity.
=> chore(Python): Pin releases to patch version

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/internaldafny/generated/dafny_src-py.dtr, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsDynamodb/runtimes/python/src/aws_cryptography_internal_dynamodb/internaldafny/generated/dafny_src-py.dtr, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, ComAmazonawsKms/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/python/src/aws_cryptography_internal_kms/internaldafny/generated/dafny_src-py.dtr, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, StandardLibrary/runtimes/python/pyproject.toml, StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/generated/dafny_src-py.dtr, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/internaldafny/generated/dafny_src-py.dtr, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/internaldafny/generated/dafny_test-py.dtr, project.properties
I manually changed this from 1.8.0 to 1.7.4.
We borked the MPL commit history, and `semantic-release` tried cutting this as 1.8.0.
=> chore(release): 1.7.4 [skip ci]

StandardLibrary/src/Sequence.dfy, StandardLibrary/src/String.dfy, StandardLibrary/src/UInt.dfy, StandardLibrary/test/TestString.dfy
HasSubString checks for a String for a Sub String.
If one is found,
Some(<index-for-start-of-sub-string>) is returned.
If not, 
None is returned.
This method was mostly written by @robin-aws 
```
chore(STD-Dafny): HasSubString
```
=> chore(STD-Dafny): HasSubString

AwsCryptographicMaterialProviders/codebuild/release-python/validate.yml, AwsCryptographyPrimitives/codebuild/release-python/validate.yml, ComAmazonawsDynamodb/codebuild/release-python/validate.yml, ComAmazonawsKms/codebuild/release-python/validate.yml, StandardLibrary/codebuild/release-python/validate.yml
Release validate step failed because the `validate` tests are built from the head of main.
The head of main has a new Dafny module that the release commit doesn't have: [StandardLibrary.Sequence](https://github.com/aws/aws-cryptographic-material-providers-library/commit/f9fb3ef40b56bedf29839daa3cfe9153ae94d932#diff-6b1486e3357d28c1914d5d449d07b9e9caea5da120af728b16cd2abb81e69656R6).
The tests fail because they're expecting to find `StandardLibrary.Sequence` in the release code, but it isn't there.
The tests should build from the release commit, not the head of main.
Fix: Tests build from the same commit the release was built from.
By submitting this pull request, I confirm that my contribution …
=> fix(Python-Release): Run validate tests from release commit

AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/internaldafny/extern/StormTrackingCMC.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/internaldafny/extern/SynchronizedLocalCMC.py
=> fix(Python): CMCs release lock for unhandled runtime exceptions

ComAmazonawsDynamodb/Model/dynamodb/model.json
Some time ago, we switched to the smithy 2.0 DynamoDB smithy model.
Unfortunately, that comes with som baggage. Namely, all the input and output structs have the `input` and `output` traits. In smithy 2.0,  this make it illegal to use those structs in other structs, which Gazelle does for the Transforms.
It seems that removing those traits has no ill effects, and so this change allows Gazelle to continue to exist.
=> fix: remove input and output traits on DynamoDB operations

.github/workflows/library_interop_tests.yml, AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, ComAmazonawsKms/runtimes/python/pyproject.toml, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, StandardLibrary/runtimes/python/pyproject.toml, StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/generated/dafny_src-py.dtr, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, project.properties
* Drop SelectOpt from MutableMap ([bdb6509](https://github.com/aws/aws-cryptographic-material-providers-library/commit/bdb65098881245dfed0f2251bd654313e31b1b89))
* Externs ([0bc1f96](https://github.com/aws/aws-cryptographic-material-providers-library/commit/0bc1f961462dd9e3821fea438e3067d543adab9c))
* formatting ([b608ab8](https://github.com/aws/aws-cryptographic-material-providers-library/commit/b608ab88e155bdb23e21f8b3f0f75116b58b182d))
* **Python-Release:** Run validate tests from release commit ([41c0c94](https://github.com/aws/aws-cryptographic-material-providers-library/commit/41c0c94aac165addcef6e75bc7bad5c1dffa16ac))
* **Python:** CMCs release lock for unhandled runtime exceptions ([#979](https://github.com/aws/aws-cryptographic-material-providers-library/issues/979)) …
=> chore(release): 1.8.0 [skip ci]

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/Structure.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/Model/AwsCryptographyKeyStoreAdminTypes.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/Model/KeyStoreAdmin.smithy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/AwsCryptographyKeyStoreAdminOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KmsUtils.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/AdminFixtures.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestDecryptEncrypt.dfy, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/ToDafny.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/ToNative.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/AwsKmsDecryptEncrypt.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystoreadmin/model/KeyManagementStrategy.java, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographyKeyStoreAdmin/AwsKmsDecryptEncrypt.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographyKeyStoreAdmin/KeyManagementStrategy.cs, AwsCryptographicMaterialProviders/runtimes/net/Generated/AwsCryptographyKeyStoreAdmin/TypeConversion.cs, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystoreadmin/dafny_to_smithy.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystoreadmin/models.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystoreadmin/smithy_to_dafny.py
Closes https://github.com/aws/aws-cryptographic-material-providers-library/pull/1013
=> feat(KSA): KMS Decrypt/Encrypt Strategy

AwsCryptographicMaterialProviders/codegen-patches/AwsCryptographicMaterialProviders/java/dafny-4.9.0.patch, AwsCryptographicMaterialProviders/codegen-patches/AwsCryptographyKeyStore/java/dafny-4.9.0.patch, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/keystore/model/CollectionOfErrors.java, AwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviders/model/CollectionOfErrors.java, AwsCryptographyPrimitives/codegen-patches/java/dafny-4.9.0.patch, AwsCryptographyPrimitives/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/primitives/model/CollectionOfErrors.java, TestVectorsAwsCryptographicMaterialProviders/codegen-patches/KeyVectors/java/dafny-4.9.0.patch, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/src/main/smithy-generated/software/amazon/cryptography/materialproviderstestvectorkeys/model/CollectionOfErrors.java
Collection of Errors is a frustrating error because it requires customer action
completely serialize it into logs.
We can make a simple fix in Java to improve the CX,
by always serializing the list into the Collection Of Error's
message.
We concatenate the given error message with 
a serialization of all the nested errors.
```
fix(Java): Improve Collection of Errors string
```
=> fix(Java): Improve Collection of Errors string

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy
=> chore: fix decrypt encrypt strategy

AwsCryptographyPrimitives/runtimes/go/ImplementationFromDafny-go/RSAEncryption/externs.go
The extern was using SignatureAlgorithm for OAEP encryption but we should be using a hash function instead of signature algorithm because
- `x509.SHA256WithRSA` is for signatures, not for OAEP encryption
- `rsa.EncryptOAEP` expects a hash function, not a signature algorithm
This PR also corrects the error message "dfewqfew" to a right error message.
=> fix: return Native Hash Algorithm instead of signature algorithm

.github/workflows/smithy-diff.yml
I have noticed that the this workflow is commenting on PRs that do not even have a Smithy Diff.
The reason is that it always compares b/w `main` and the PR's Head.
I suggest the workflow check the PRs diff,
as compared to the diff b/w PR's HEAD and main.
```
chore(GHW): Smithy-Diff should be on the PR diff, not diff b/w main 
```
=> chore(GHW): Smithy-Diff should be on the PR diff, not diff b/w main

AwsCryptographicMaterialProviders/runtimes/rust/src/ecdh.rs
Make the ECDH extern function `X962_to_X509` `pub` instead of `pub(crate)` to use it in the examples, in order to avoid code duplication.
=> chore(rust-ecdh-extern): Update to use extern function in ESDK examples

AwsCryptographicMaterialProviders/runtimes/rust/src/ecdh.rs
Reverts aws/aws-cryptographic-material-providers-library#1076
Once aws-lc-rs supports the various formats we need, we want to drop the dependence on aws-lc-sys.
If we keep the function public, we will have to support it forever. This will make the above update a blocking change. For Rust ECDH examples, we will create a function that mimics `X962_to_X509` so that we can update it with the aws-lc-rs conversions once they are supported.
=> chore(rust-ecdh-extern): Rollback update to extern function

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/ApplyMutation.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy
=> fix: use correct client depending on operation

AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/Constants.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/DdbHelper.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/Fixtures.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/KeyStoreProvider.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/DescribeMutationExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationDecryptEncryptExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationResumeExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationsProvider.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/ScanForInFlightMutations.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/ValidateKeyStoreItem.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/DescribeMutationTest.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessOriginalInFlightTest.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessOriginalInFlightTestDecryptEncrypt.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessTerminalInFlightTest.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsAccessTerminalInFlightTestDecryptEncrypt.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationSystemKeyKMSExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationSystemKeyTrustStorage.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationsSystemKeyKMSTamper.java
=> test(KSA-Java): assert deletion of Index/Commitment at end of Mutation

AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/Fixtures.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationsProvider.java, AwsCryptographicMaterialProviders/runtimes/java/src/examples/java/software/amazon/cryptography/example/hierarchy/mutations/MutationsSystemKeyTrustExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/DescribeMutationTest.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationSystemKeyKMSExample.java, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationsSystemKeyKMSTamper.java
This ensures that our implementation is correct,
as if it was not,
the incorrect KMS Client would be used,
and the request would fail.
=> test(KSA): Utilize Limit KMS Clients in Mutation D/E test

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/DefaultKeyStorageInterface.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/ApplyMutation.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KmsUtils.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationErrorRefinement.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy, AwsCryptographicMaterialProviders/runtimes/java/src/testExamples/java/software/amazon/cryptography/example/hierarchy/mutations/DoNotVersionTest.java, StandardLibrary/src/Time.dfy
1. Implement `doNotVersion` behavior in Initialize Mutation
2. Refactor Initialize, Apply, and Mutations.dfy to simplify Pre/Post conditions for Mutate
In a separate PR,
I will revise the Documentation trait for `doNotVersion` to explain
when it is a good idea to Version and when it is not needed.
=> feat(KSA): DoNotVersion for Initialize Mutation

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationStateStructures.dfy
Dafny has some sensitivity with module imports that,
when this library is used in a Java environment with the DB-ESDK,
end up causing duplicated class paths.
```
[ht:validateClasspath]      for the following classes:
[ht:validateClasspath]          Sets_Compile.__default
[ht:validateClasspath]          Maps_Compile.__default
```
This occurs because the Mutation feature branch added 
a dependency on Dafny-lang's library's Maps and Sets modules,
which are already dependencies of the DB-ESDK.
Dafny's `library` flag would have avoided this,
IF and ONLY IF the DB-ESDK is compiled by Dafny 
**knowing** that the MPL uses Maps and Sets.
Because the MPL added these dependencies,
it fails class path validation with older DB-ESDKs.
We do not have a …
=> fix(MPL): remove un-used imports

AwsCryptographicMaterialProviders/runtimes/rust/src/dafny_libraries.rs, AwsCryptographicMaterialProviders/runtimes/rust/src/rsa.rs, AwsCryptographicMaterialProviders/runtimes/rust/src/storm_tracker.rs, AwsCryptographicMaterialProviders/runtimes/rust/src/time.rs, AwsCryptographicMaterialProviders/runtimes/rust/src/timer.rs, AwsCryptographicMaterialProviders/runtimes/rust/src/uuid.rs, AwsCryptographyPrimitives/runtimes/rust/Cargo.toml, ComAmazonawsDynamodb/runtimes/rust/Cargo.toml, ComAmazonawsKms/runtimes/rust/Cargo.toml, StandardLibrary/Makefile, StandardLibrary/runtimes/go/ImplementationFromDafny-go/FileIO/externs.go, StandardLibrary/runtimes/go/ImplementationFromDafny-go/Time_/externs.go, StandardLibrary/runtimes/java/src/main/java/DafnyLibraries/FileIO.java, StandardLibrary/runtimes/java/src/main/java/Time/__default.java, StandardLibrary/runtimes/net/Extern/FileIO.cs, StandardLibrary/runtimes/net/Extern/Time.cs, StandardLibrary/runtimes/net/STD.csproj, StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/extern/DafnyLibraries.py, StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/extern/Time.py, StandardLibrary/runtimes/rust/Cargo.toml, StandardLibrary/runtimes/rust/copy_externs.sh, StandardLibrary/runtimes/rust/src/dafny_libraries.rs, StandardLibrary/runtimes/rust/src/lib.rs, StandardLibrary/src/Time.dfy, StandardLibrary/test/TestComputeSetToOrderedSequenceUInt8Less.dfy, StandardLibrary/test/TestString.dfy
=> chore: add new externs for file append and cpu time

StandardLibrary/runtimes/go/ImplementationFromDafny-go/FileIO/externs.go, StandardLibrary/runtimes/go/ImplementationFromDafny-go/Time_/externs.go, StandardLibrary/test/GetOpt.dfy, StandardLibrary/test/TestString.dfy
=> fix: improve golang externs

AwsCryptographicMaterialProviders/runtimes/rust/Cargo.toml, AwsCryptographicMaterialProviders/runtimes/rust/src/aes_gcm.rs, AwsCryptographicMaterialProviders/runtimes/rust/src/ecdh.rs, AwsCryptographyPrimitives/runtimes/rust/Cargo.toml, TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/VectorsComposition/AllAlgorithmSuites.dfy, TestVectorsAwsCryptographicMaterialProviders/runtimes/rust/Cargo.toml
=> fix: re-enable aes_gcm_192

.github/workflows/library_go_tests.yml
There are two tests done for test vectors in CI. 
1. Interop test: Encrypt in one language and decrypt in another
2. library_runtime_tests: where testvector is tested in the same language by running `make test_go`.
We were missing the 2nd test. So, this PR adds it.
```
chore: Add missing testvectors test
```
=> chore: Add missing testvectors test 

AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/python/pyproject.toml, StandardLibrary/runtimes/python/pyproject.toml, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/pyproject.toml
poetry released a new major version: https://pypi.org/project/poetry/2.0.0/
Python projects picked this up automatically because they didn't specify a maximum version for poetry.
This is bad, since this is a breaking change, and it broke building new Python libraries.
This doesn't break customers using the already-distributed MPL packages. This only breaks the build system, and we only rebuild the library in CI and for releases. I can install the published MPL from PyPI and use it without issues.
=> chore(Python): Restrict poetry-core to <2.0.0

.github/workflows/check-files.yml, .github/workflows/check_dafny_runtime_versions.yml, .github/workflows/check_only_keyword.yml, .github/workflows/ci_static-analysis.yaml, .github/workflows/dafny_verify_version.yaml, .github/workflows/dafny_version.yaml, .github/workflows/duvet.yaml, .github/workflows/library_codegen.yml, .github/workflows/library_format.yml, .github/workflows/library_go_tests.yml, .github/workflows/library_interop_tests.yml, .github/workflows/library_java_tests.yml, .github/workflows/library_net_tests.yml, .github/workflows/library_python_tests.yml, .github/workflows/library_rust_tests.yml, .github/workflows/nightly_dafny.yml, .github/workflows/pull.yml, .github/workflows/stale_issue.yml, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystore/smithy_to_dafny.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_materialproviders/dafny_to_smithy.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_materialproviders/smithy_to_dafny.py, AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/dafny_to_smithy.py, AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/smithygenerated/aws_cryptography_primitives/smithy_to_dafny.py
=> chore: Bump Smithy-Dafny, re-polymorph, use ubuntu-22.04

AwsCryptographicMaterialProviders/Makefile, AwsCryptographicMaterialProviders/runtimes/go/ImplementationFromDafny-go/awscryptographykeystoreadminsmithygenerated/to_dafny.go, AwsCryptographicMaterialProviders/runtimes/go/ImplementationFromDafny-go/awscryptographykeystoreadminsmithygenerated/to_native.go, AwsCryptographicMaterialProviders/runtimes/go/ImplementationFromDafny-go/awscryptographykeystoreadminsmithygeneratedtypes/types.go, AwsCryptographicMaterialProviders/runtimes/go/ImplementationFromDafny-go/awscryptographykeystoresmithygenerated/to_dafny.go, AwsCryptographicMaterialProviders/runtimes/go/ImplementationFromDafny-go/awscryptographykeystoresmithygenerated/to_native.go, AwsCryptographicMaterialProviders/runtimes/go/ImplementationFromDafny-go/awscryptographykeystoresmithygeneratedtypes/errors.go, AwsCryptographicMaterialProviders/runtimes/go/TestsFromDafny-go/awscryptographykeystoreadminsmithygenerated/to_dafny.go, AwsCryptographicMaterialProviders/runtimes/go/TestsFromDafny-go/awscryptographykeystoreadminsmithygenerated/to_native.go, AwsCryptographicMaterialProviders/runtimes/go/TestsFromDafny-go/awscryptographykeystoreadminsmithygeneratedtypes/types.go, AwsCryptographicMaterialProviders/runtimes/go/TestsFromDafny-go/awscryptographykeystoresmithygenerated/to_dafny.go, AwsCryptographicMaterialProviders/runtimes/go/TestsFromDafny-go/awscryptographykeystoresmithygenerated/to_native.go, AwsCryptographicMaterialProviders/runtimes/go/TestsFromDafny-go/awscryptographykeystoresmithygeneratedtypes/errors.go, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystoreadmin/dafny_to_smithy.py, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/smithygenerated/aws_cryptography_keystoreadmin/smithy_to_dafny.py
1. Modify the AwsCryptographicMaterialProvider Makefile for Go
2. Re-poly Go
3. Re-poly Python
```
fix(KeyStoreAdmin): Go support
```
=> fix(KeyStoreAdmin): Go support

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/python/pyproject.toml, StandardLibrary/runtimes/python/pyproject.toml, TestVectorsAwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, project.properties
=> chore: allow local testing

.prettierignore
=> chore: expand prettier ignore

.github/workflows/library_dafny_verification.yml, .github/workflows/library_go_tests.yml, .github/workflows/library_interop_tests.yml, .github/workflows/library_java_tests.yml, .github/workflows/library_net_tests.yml, .github/workflows/library_python_tests.yml, .github/workflows/library_rust_tests.yml, StandardLibrary/src/Base64Lemmas.dfy
- Temporarily remove macOS from CI so that CI starts working because of https://github.com/dotnet/sdk/issues/46857.
- Needed to break 2 lemma in Standard library because verification was going out of resource.
=> chore: remove mac os from CI and refactor base64Lemmas

cfn/ESDK-Hierarchy-CI.yaml
1. Adds `kms:GenerateRandom` permission to `Hierarchical-GitHub-KMS-Key-Policy` to allow CI role to support HV-2.
=> chore: add kms:GenerateRandom permission to CI role

.github/PULL_REQUEST_TEMPLATE.md
I prefer using Mark Down headings over italics to delineate the sections of a PR description.
In general, 
I find we either completely ignore the descriptions (author & reviewer),
or we want to use them to detail a significant amount of detail.
For the second case,
I think headings is more useful.
=> refactor: Mark Down headings for the PR template

.github/workflows/library_interop_tests.yml, .github/workflows/manual.yml, .github/workflows/pull.yml, .github/workflows/push.yml
HV-2 early Milestones
Disable CI for Rust & Go for now; we will re-enable when we can or when we need to.
```
ci(Go, Rust): disable for current HV-2 work
```
=> ci(Go, Rust): disable for current HV-2 work

AwsCryptographicMaterialProviders/runtimes/net/Extern/StormTrackingCMC.cs, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/internaldafny/extern/StormTrackingCMC.py
https://t.corp.amazon.com/P178880667
Make this change:
https://github.com/aws/aws-cryptographic-material-providers-library/pull/1024
in CSharp and Python
```
<message>
```
=> chore: add proper sleep handling in StormTracker for Pythn and .NET

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/GetKeys.dfy
If the KMS-ARN is an alias or otherwise an invalid, 
it is was read from Storage in-correctly the Stored item was invalid;
it was NOT KMS-ARN disagreement b/w the KMS Configuration
and the Branch Key.
```
<message>
```
=> fix(Dafny): correct error message

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/GetKeys.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestGetKeys.dfy
Adds:
1. TestGetKeysHappyCase (all 3)
2. TestKeyWithIncorrectKmsKeyArn (all 3)
3. TestGetKeyWrongLogicalKeyStoreName (all 3)
4. TestGetKeyDoesNotExistFails (all 3)(covers hv1 and hv2)
5. TestGetKeysWithNoClients (all 3)
```
```
=> chore(dafny): add test for get keys 

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestGetKeys.dfy
Pulling out get keys from storage test from VerifyGetKeys into its own function.
```
chore(dafny): add VerifyGetKeysFromStorage to test 
```
=> chore(dafny): add VerifyGetKeysFromStorage to test

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/TestGetKeys.dfy
=> chore(dafny): refactor HV1 MRK test to use helper methods

AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/src/CanonicalEncryptionContext.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/HierarchicalVersionUtils.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/AwsCryptographyKeyStoreAdminOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/BKSAOperationUtils.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/CreateKeysHV2.dfy
```
fix(dafny): BKSA Create Key HV-2
It is difficult for Dafny to keep track of the KMS Encrypt requests,
as the three are nearly identical,
with the exception of the Branch Key Context Digest (bkcd).
But a SHA-384 Digest is only "socially" injective;
the domain of SHA-384 is greater than the range.
Instead,
we can break the KMS Encrypt request into a helper
method that is much easier to reason about.
Then, 
we do not need to track the different KMS requests.
```
=> fix(dafny): BKSA CreateKey formal verification

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/DefaultKeyStorageInterface.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/StorageHelpers.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/Structure.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy, Examples/java/src/main/java/software/amazon/cryptography/example/DdbHelper.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/ValidateKeyStoreItem.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/DoNotVersionTest.java
We treat the `hierarchy-version` attribute as, 
as @kessplas put it,
a "schema version".
For Branch Key Items, the schema dictates how to decrypt and validate the cryptographic material.
For Mutation Items, the schema dictates if `hierarchy-version` is in the Mutation Commitment.
I also refactored the Storage Layer's Helpers,
which will help us have better errors in the future.
```
```
=> fix(dafny): BKS Mutation Items treat `hierarchy-version` as schema version

cfn/CI.yaml, cfn/ESDK-Hierarchy-CI.yaml
- Creates KeyStoreStaticTable DynamoDB table 
- Creates StaticKeyStoreTableReadOnly IAM policy for read-only access
- Updated GitHub CI role to use read-only policy
```
```
=> chore: Create Static Key Store table for storing static branch keys

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestMutateToHV2FromHV1.dfy
- Moves TestMutateToHV2FromHV1 to mutation 
- As per my comment in my last PR https://github.com/aws/aws-cryptographic-material-providers-library/pull/1461#discussion_r2054804000
```
refactor(dafny): move TestMutateToHV2FromHV1 to mutation directory 
```
=> refactor(dafny): move TestMutateToHV2FromHV1 to mutation directory 

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/Structure.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/AdminFixtures.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestMutateToHV2FromHV1.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestMutationHappyPath.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestHv2KmsExceptions.dfy
=> feat(dafny): mutate HV-2 to HV-2 without new version

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KmsUtils.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/InitializeMutation.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/KeyStoreAdminErrorMessages.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/Mutations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/Mutations/TestMutateHierarchyVersion.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/test/TestAdminHV1Only.dfy
=> chore(dafny): support kms simple for v1 to v1 mutations

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/CreateKeys.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/AwsCryptographyKeyStoreAdminOperations.dfy
In Branch Key Creation,
until the Encryption Context 
is passed to `Structure.DecryptOnlyBranchKeyEncryptionContext`,
the Encryption Context is exactly as the customer intended it to be.
Thus, for `hierarchy-version-2`,
we do not need to do any transforms on the Encryption Context
before it is sent to KMS;
in fact, we should ensure that we do not any transforms.
```
chore(dafny): remove redundant EC checks
```
=> chore(dafny): BKS CreateKey remove redundant EC checks for HV-2

AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/MutationErrorRefinement.dfy, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStoreAdmin/src/SystemKeyErrorRefinement.dfy, Examples/java/build.gradle.kts, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/KmsMutationExceptionTest.java
=> chore(dafny): refine KMS Error mapping correctly to MutationTo/From exception

.github/workflows/library_interop_tests.yml, AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/test/Fixtures.dfy
- bumping to get the fix for Unicode handling in JSON (Commit: [fd67943663b201f789aa7a24b9c9d8ff192a6cb1](https://github.com/dafny-lang/libraries/commit/fd67943663b201f789aa7a24b9c9d8ff192a6cb1))
- I also cherrypicked [377de796f001ae21f69ac0e10f57709d0e6fa1ef](https://github.com/aws/aws-cryptographic-material-providers-library/commit/377de796f001ae21f69ac0e10f57709d0e6fa1ef) as the fixture in mutations/mutatons was not updated and the test will fail without it.
- did formatting as well.
```
chore(dafny): bump libraries submodule to latest commit 
```
=> chore(dafny): bump libraries submodule to latest commit 

.github/actions/install_smithy_dafny_codegen_dependencies/action.yml, .github/actions/polymorph_codegen/action.yml, .github/workflows/library_codegen.yml, .github/workflows/library_dafny_verification.yml, .github/workflows/library_format.yml, .github/workflows/library_go_tests.yml, .github/workflows/library_interop_tests.yml, .github/workflows/library_java_tests.yml, .github/workflows/library_net_tests.yml, .github/workflows/library_python_tests.yml, .github/workflows/library_rust_tests.yml, .github/workflows/nightly_dafny.yml
* Updated `smithy-dafny` to pick up the change to pass `--enforce-determinism` for newer Dafnies: https://github.com/smithy-lang/smithy-dafny/pull/789
* Moved codgen CLI dependencies such as Java 17 into the common `install_smithy_dafny_codegen_dependencies/action.yml` workflow
* Made workflows always call this action, since the shared makefile now calls the codegen CLI `if-dafny-at-least` command
* Disabled checking formatting in the nightly, since that often hits false positives.
Manual build against Dafny's `nightly-latest` (just before removing `library_format.yml` from nightly): https://github.com/aws/aws-cryptographic-material-providers-library/actions/runs/15200158182
=> chore(CI): Fix nightly build (mostly)

Examples/java/src/main/java/software/amazon/cryptography/example/Constants.java, Examples/java/src/main/java/software/amazon/cryptography/example/DdbHelper.java, Examples/java/src/main/java/software/amazon/cryptography/example/hierarchy/KeyStoreProvider.java, Examples/java/src/main/java/software/amazon/cryptography/example/hierarchy/mutations/MutationKmsSimpleExample.java, Examples/java/src/main/java/software/amazon/cryptography/example/hierarchy/mutations/MutationsProvider.java, Examples/java/src/main/java/software/amazon/cryptography/example/hierarchy/mutations/MutationsSystemKeyTrustExample.java, Examples/java/src/main/java/software/amazon/cryptography/example/hierarchy/mutations/ScanForInFlightMutations.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/ExampleTests.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/StaticMutation.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/ValidateKeyStoreItem.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/concurrent/ConcurrentConditionCheckWriteTest.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/concurrent/StorageVersionReadConcurrencyTests.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/concurrent/StorageWriteReadConcurrencyTests.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/concurrent/testng-parallel.xml, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/DescribeMutationTest.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/DoNotVersionTest.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/KmsInFlightMutationAccessDeniedRunner.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/KmsInFlightMutationV1ToV1Test.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/KmsInFlightMutationV1ToV2Test.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/KmsInFlightMutationV2ToV2Test.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/ScanForInFlightMutationsTest.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationSystemKeyKMSExample.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationSystemKeyTrustStorage.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationToHV2ProperlyHandlesEmptyEncryptionContextKey.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationsSystemKeyKMSTamper.java, Examples/java/src/test/java/software/amazon/cryptography/example/hierarchy/mutations/TestMutationsWithEscapeCharactersInEC.java
- Added a bunch of copyright headers to Java code that was missing them
- Java Integ test for JSON handling of Escape characters
```
test(Dafny): Java Integ Test for Escape Chars
```
=> test(Dafny): Java Integ Test for Escape Chars

AwsCryptographicMaterialProviders/runtimes/java/build.gradle.kts, cfn/CB.yml, codebuild/release/release-prod.yml
n/a
Need to migrate how we publish to Maven. See https://github.com/aws/aws-encryption-sdk-java/pull/2117/files in the ESDK. This project uses Gradle though so the change is slightly different. 
**NOTE** I couldn't find a way to enable [auto publish](https://central.sonatype.org/publish/publish-portal-maven/#automatic-publishing) in the Gradle plugin, so the release may require additional steps. 
```
chore(java): migrate to Nexus Central for Maven publishing
Deployed CB.yaml change via change set ID:
arn:aws:cloudformation:us-west-2:587316601012:changeSet/AWS-MPL-Java-Staging-Maybe-Nexus-2025-06-10/04f37e32-a5a6-45f3-916a-b061bc145e27
To Stack:
arn:aws:cloudformation:us-west-2:587316601012:stack/AWS-MPL-Java-Staging/193816b0-f98b-11ed-95bb-0a13e345bcb7
```
By submitting this pull request, …
=> chore(java): migrate to Nexus Central for Maven publishing

AwsCryptographyPrimitives/runtimes/python/pyproject.toml
Note that CVE-2024-12797 does not apply to how the library uses pyca.
The library only uses pyca for local cryptography and AS1N parsing, never to process public TLS certs.
All web requests issued while using the library are issued via the AWS SDK for Python (boto),
which handles certs via a different cryptographic provider.
But, consumers of the MPL-Python could also directly use pyca,
and therefore use  pyca to process TLS certs;
those consumers resolution path to the TLS issue MAY be more complicated IF the MPL does not bump pyca.
Ran:
```
poetry add cryptography@^44.0
```
```
chore(Python): bump pyca to 44.0
On release, resolves:
https://github.com/aws/aws-cryptographic-material-providers-library/issues/1552
```
By submitting this pull request, I confirm that my contribution is made …
=> chore(Python): bump pyca to 44.0

AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml, AwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptographic_material_providers/internaldafny/generated/dafny_src-py.dtr, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/python/src/aws_cryptography_primitives/internaldafny/generated/dafny_src-py.dtr, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsDynamodb/runtimes/python/src/aws_cryptography_internal_dynamodb/internaldafny/generated/dafny_src-py.dtr, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, ComAmazonawsKms/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/python/src/aws_cryptography_internal_kms/internaldafny/generated/dafny_src-py.dtr, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, StandardLibrary/runtimes/python/pyproject.toml, StandardLibrary/runtimes/python/src/smithy_dafny_standard_library/internaldafny/generated/dafny_src-py.dtr, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/src/aws_cryptography_materialproviders_test_vectors/internaldafny/generated/dafny_src-py.dtr, TestVectorsAwsCryptographicMaterialProviders/runtimes/python/test/internaldafny/generated/dafny_test-py.dtr, project.properties
* **dafny:** bump Dafny libraries for JSON fix ([#1517](https://github.com/aws/aws-cryptographic-material-providers-library/issues/1517)) ([d8679e5](https://github.com/aws/aws-cryptographic-material-providers-library/commit/d8679e517ae3bc3b074325f849b5cb6c252c8f18))
* **dafny:** BK fix to extract encryption context for branch key materials ([#1523](https://github.com/aws/aws-cryptographic-material-providers-library/issues/1523)) ([95856ac](https://github.com/aws/aws-cryptographic-material-providers-library/commit/95856acd01ad26460a09eb171f2793a3109bfdbd))
* **dafny:** don't recalculate RSA key on every decrypt ([#1448](https://github.com/aws/aws-cryptographic-material-providers-library/issues/1448)) ([f318912](https://github.com/aws/aws-cryptographic-material-providers-library/commit/f3189 …
=> chore: 1.11.0 [skip ci]

codebuild/release/release-prod.yml, codebuild/release/validate-release.yml, codebuild/staging/release-staging.yml, codebuild/staging/validate-staging.yml
Setting because it defaults to 5.0 in the release.
Failure:
```
BUILD FAILED in 59s
209 | Makefile:34: warning: overriding recipe for target 'polymorph_rust'
210 | /codebuild/output/src1145001677/src/github.com/aws/aws-cryptographic-material-providers-library/smithy-dafny/SmithyDafnyMakefile.mk:457: warning: ignoring old recipe for target 'polymorph_rust'
211 | dotnet restore runtimes/net/
212 | Determining projects to restore...
213 | /root/.dotnet/sdk/5.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/codebuild/output/src1145001677/src/github.com/aws/aws-cryptographic-material-pr …
```
=> chore(java): set .NET version to 6.0 in release workflow

AwsCryptographicMaterialProviders/codebuild/release-python/prod-release.yml, AwsCryptographicMaterialProviders/codebuild/release-python/test-release.yml, AwsCryptographicMaterialProviders/codebuild/release-python/validate.yml, AwsCryptographyPrimitives/codebuild/release-python/prod-release.yml, AwsCryptographyPrimitives/codebuild/release-python/test-release.yml, AwsCryptographyPrimitives/codebuild/release-python/validate.yml, ComAmazonawsDynamodb/codebuild/release-python/prod-release.yml, ComAmazonawsDynamodb/codebuild/release-python/test-release.yml, ComAmazonawsDynamodb/codebuild/release-python/validate.yml, ComAmazonawsKms/codebuild/release-python/prod-release.yml, ComAmazonawsKms/codebuild/release-python/test-release.yml, ComAmazonawsKms/codebuild/release-python/validate.yml, StandardLibrary/codebuild/release-python/prod-release.yml, StandardLibrary/codebuild/release-python/test-release.yml, StandardLibrary/codebuild/release-python/validate.yml
Related PR https://github.com/aws/aws-cryptographic-material-providers-library/pull/1570
```
ind ./dafny/**/src/ ./src/ -name 'Index.dfy' | sed -e 's/^/include "/' -e 's/$/"/' | dafny \
translate py \
--stdin \
--no-verify \
--cores:2 \
Downloading https://services.gradle.org/distributions/gradle-7.6-bin.zip ...........10%............20%...........30%............40%............50%...........60%............70%............80%...........90%............100% \
--optimize-erasable-datatype-wrapper:false \
--unicode-char:false \
--function-syntax:3 \
--output runtimes/python/dafny_src \
--allow-warnings --allow-external-contracts \
\
--python-module-name=smithy_dafny_standard_library.internaldafny.generated \
\
\
\
find: ‘./dafny/**/src/’: No such file or directory
*** Error: Command-line …
```
=> chore(CI): add setup_net for python release workflow

AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/python/pyproject.toml
All CI should pass except the Python CI and the interop tests.
(This release PR points Python libraries to unpublished dependencies, so Python libraries will fail.)
```
chore: 1.11.0 [skip CI]
```
=> chore: 1.11.0 [skip CI] for python libraries

StandardLibrary/test/TestString.dfy
For Context(Pasting Notes from MCM)
The validate_staging_release step failed with a non-transient error:
```
TestStrings.TestBadFileIO: FAILED
test/TestString.dfy(63,4): expectation violation
```
Source code: https://github.com/aws/aws-cryptographic-material-providers-library/blame/main/StandardLibrary/test/TestString.dfy#L60-L64
The test touches OS-specific behavior. I’d bet there’s something that works on GHA runners and locally, but not on the CodeBuild Linux image.
```
chore(dafny): remove negative test
```
=> chore(dafny): remove negative test for codebuild runner

cfn/CI.yaml
MPL-Python release validation failed with 
```
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::587316601012:assumed-role/codebuild-AWS-MPL-Python-test-service-role/AWSCodeBuild-98c5174f-9905-4a31-b66f-a2f020c8add5 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2
```
```
chore(cfn): add trusted policy for optools mpl-python roles
```
=> chore(cfn): add trusted policy for optools mpl-python roles

.github/workflows/issue-notification.yml, .github/workflows/slack-notification.yml
Workflow (which starts on [issue](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues)) is only triggered when workflow is on default branch. But, to test if it works I have triggered on push the workflow in commit [535c19d](https://github.com/aws/aws-cryptographic-material-providers-library/pull/1632/commits/535c19dc032fe1324005d1a003673f3aa6e33bea).
My plan is to add everyone to the channel, once its merged and I test it.
```
chore(CI): send slack message on new GHI 
```
=> chore(CI): send slack message on new GHI 

.github/workflows/issue-notification.yml
`issue_comment` gets triggered in issue comments and PR comments. Updating to not trigger in PR comments. See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
```
chore(ci): update to not trigger workflow on PR comments 
```
=> chore(ci): update to not trigger workflow on PR comments

AwsCryptographicMaterialProviders/runtimes/net/AssemblyInfo.cs, AwsCryptographicMaterialProviders/runtimes/net/MPL.csproj, AwsCryptographicMaterialProviders/runtimes/python/pyproject.toml, AwsCryptographyPrimitives/runtimes/net/AssemblyInfo.cs, AwsCryptographyPrimitives/runtimes/net/Crypto.csproj, AwsCryptographyPrimitives/runtimes/python/pyproject.toml, CHANGELOG.md, ComAmazonawsDynamodb/runtimes/net/AssemblyInfo.cs, ComAmazonawsDynamodb/runtimes/net/ComAmazonawsDynamodb.csproj, ComAmazonawsDynamodb/runtimes/python/pyproject.toml, ComAmazonawsKms/runtimes/net/AWS-KMS.csproj, ComAmazonawsKms/runtimes/net/AssemblyInfo.cs, ComAmazonawsKms/runtimes/python/pyproject.toml, StandardLibrary/runtimes/net/AssemblyInfo.cs, StandardLibrary/runtimes/net/STD.csproj, StandardLibrary/runtimes/python/pyproject.toml, project.properties
* **dafny:** add Rust and Go to supported languages  ([#1492](https://github.com/aws/aws-cryptographic-material-providers-library/issues/1492)) ([87ab402](https://github.com/aws/aws-cryptographic-material-providers-library/commit/87ab40233096739f2aa709fdcd948ce7452c7d04))
* **dafny:** append our user agent in KMS client ([#1564](https://github.com/aws/aws-cryptographic-material-providers-library/issues/1564)) ([03d03ac](https://github.com/aws/aws-cryptographic-material-providers-library/commit/03d03ac1f3591885bcc583efb988602ed129c3c5))
* **dafny:** remove negative test for codebuild runner ([#1603](https://github.com/aws/aws-cryptographic-material-providers-library/issues/1603)) ([8b45e40](https://github.com/aws/aws-cryptographic-material-providers-library/commit/8b45e40e9fa081e277837946e5 …
=> chore: 1.11.1 [skip ci]

.github/workflows/library_go_tests.yml
Go released go 1.25 on 2025-08-12. So, I am adding this test. On ORR, we had decided we will test against same version AWS SDK go does its test on. AWS SDK Go test against all the versions they support. They haven't added 1.25 to their matrix but they will soon.
```
chore(go): add go 1.25 to CI 
```
=> chore(go): add go 1.25 to CI

.releaserc.cjs, ComAmazonawsKms/runtimes/python/src/aws_cryptography_internal_kms/internaldafny/extern/Com_Amazonaws_Kms.py, ComAmazonawsKms/runtimes/python/src/aws_cryptography_internal_kms/internaldafny/extern/__init__.py, ComAmazonawsKms/src/Index.dfy
Before Change:
`"userAgent": "Boto3/1.40.10 md/Botocore#1.40.10 ua/2.1 os/macos#24.5.0 md/arch#arm64 lang/python#3.12.11 md/pyimpl#CPython m/Z,b,D cfg/retry-mode#legacy Botocore/1.40.10"`
After Change
`"userAgent": "Boto3/1.40.10 md/Botocore#1.40.10 ua/2.1 os/macos#24.5.0 md/arch#arm64 lang/python#3.12.11 md/pyimpl#CPython m/b,D,Z cfg/retry-mode#legacy Botocore/1.40.10 AwsCryptographicMPL/Python/1.11.0"`
```
chore(python): add user agent suffix to kms requests
```
=> chore(python): add user agent suffix to kms requests
